'''
MIT License

Copyright (c) 2024 FSC Lab

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
'''

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_Sampler.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WaterSamplingGroundControlStation(object):
    def setupUi(self, WaterSamplingGroundControlStation):
        WaterSamplingGroundControlStation.setObjectName("WaterSamplingGroundControlStation")
        WaterSamplingGroundControlStation.resize(1341, 857)
        self.Initialization_Tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Initialization_Tab.setFont(font)
        self.Initialization_Tab.setObjectName("Initialization_Tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Initialization_Tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 941, 761))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.InitVLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.InitVLayout.setContentsMargins(0, 0, 0, 0)
        self.InitVLayout.setObjectName("InitVLayout")
        self.InitTitle = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.InitTitle.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.InitTitle.setFont(font)
        self.InitTitle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.InitTitle.setObjectName("InitTitle")
        self.InitVLayout.addWidget(self.InitTitle)
        self.Welcome = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Welcome.setWordWrap(True)
        self.Welcome.setObjectName("Welcome")
        self.InitVLayout.addWidget(self.Welcome)
        self.ROSCoreInfo = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.ROSCoreInfo.setWordWrap(True)
        self.ROSCoreInfo.setObjectName("ROSCoreInfo")
        self.InitVLayout.addWidget(self.ROSCoreInfo)
        self.StartROSCore = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.StartROSCore.setObjectName("StartROSCore")
        self.InitVLayout.addWidget(self.StartROSCore)
        self.MAVROSInfo = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.MAVROSInfo.setFrameShadow(QtWidgets.QFrame.Plain)
        self.MAVROSInfo.setWordWrap(True)
        self.MAVROSInfo.setObjectName("MAVROSInfo")
        self.InitVLayout.addWidget(self.MAVROSInfo)
        self.StartMAVROS = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.StartMAVROS.setObjectName("StartMAVROS")
        self.InitVLayout.addWidget(self.StartMAVROS)
        self.OFFBOARDInfo = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.OFFBOARDInfo.setWordWrap(True)
        self.OFFBOARDInfo.setObjectName("OFFBOARDInfo")
        self.InitVLayout.addWidget(self.OFFBOARDInfo)
        self.StartOffboard = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.StartOffboard.setObjectName("StartOffboard")
        self.InitVLayout.addWidget(self.StartOffboard)
        WaterSamplingGroundControlStation.addTab(self.Initialization_Tab, "")
        self.AutonomousFlightMode_Tab = QtWidgets.QWidget()
        self.AutonomousFlightMode_Tab.setObjectName("AutonomousFlightMode_Tab")
        self.AutonomousTitle = QtWidgets.QLabel(self.AutonomousFlightMode_Tab)
        self.AutonomousTitle.setGeometry(QtCore.QRect(30, 15, 481, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.AutonomousTitle.setFont(font)
        self.AutonomousTitle.setObjectName("AutonomousTitle")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 80, 301, 181))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.GPSDataLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.GPSDataLayout.setContentsMargins(0, 0, 0, 0)
        self.GPSDataLayout.setObjectName("GPSDataLayout")
        self.GPSLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.GPSLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.GPSLabel.setObjectName("GPSLabel")
        self.GPSDataLayout.addWidget(self.GPSLabel)
        self.GPSHLayout = QtWidgets.QHBoxLayout()
        self.GPSHLayout.setObjectName("GPSHLayout")
        self.LatLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.LatLabel.setObjectName("LatLabel")
        self.GPSHLayout.addWidget(self.LatLabel)
        self.LongLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.LongLabel.setObjectName("LongLabel")
        self.GPSHLayout.addWidget(self.LongLabel)
        self.AltLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.AltLabel.setObjectName("AltLabel")
        self.GPSHLayout.addWidget(self.AltLabel)
        self.GPSDataLayout.addLayout(self.GPSHLayout)
        self.GPS_DISP = QtWidgets.QHBoxLayout()
        self.GPS_DISP.setObjectName("GPS_DISP")
        self.LatGPS_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_2)
        self.LatGPS_DISP.setObjectName("LatGPS_DISP")
        self.GPS_DISP.addWidget(self.LatGPS_DISP)
        self.LongGPS_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_2)
        self.LongGPS_DISP.setObjectName("LongGPS_DISP")
        self.GPS_DISP.addWidget(self.LongGPS_DISP)
        self.AltGPS_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_2)
        self.AltGPS_DISP.setObjectName("AltGPS_DISP")
        self.GPS_DISP.addWidget(self.AltGPS_DISP)
        self.GPSDataLayout.addLayout(self.GPS_DISP)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(350, 270, 291, 191))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.IMULayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.IMULayout.setContentsMargins(0, 0, 0, 0)
        self.IMULayout.setObjectName("IMULayout")
        self.IMULabel = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.IMULabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.IMULabel.setObjectName("IMULabel")
        self.IMULayout.addWidget(self.IMULabel)
        self.IMUHLayout = QtWidgets.QHBoxLayout()
        self.IMUHLayout.setObjectName("IMUHLayout")
        self.XLabel0 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.XLabel0.setObjectName("XLabel0")
        self.IMUHLayout.addWidget(self.XLabel0)
        self.YLabel0 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.YLabel0.setObjectName("YLabel0")
        self.IMUHLayout.addWidget(self.YLabel0)
        self.ZLabel0 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.ZLabel0.setObjectName("ZLabel0")
        self.IMUHLayout.addWidget(self.ZLabel0)
        self.IMULayout.addLayout(self.IMUHLayout)
        self.IMU_DISP = QtWidgets.QHBoxLayout()
        self.IMU_DISP.setObjectName("IMU_DISP")
        self.X_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_4)
        self.X_DISP.setObjectName("X_DISP")
        self.IMU_DISP.addWidget(self.X_DISP)
        self.Y_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_4)
        self.Y_DISP.setObjectName("Y_DISP")
        self.IMU_DISP.addWidget(self.Y_DISP)
        self.Z_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_4)
        self.Z_DISP.setDigitCount(6)
        self.Z_DISP.setObjectName("Z_DISP")
        self.IMU_DISP.addWidget(self.Z_DISP)
        self.IMULayout.addLayout(self.IMU_DISP)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(30, 270, 301, 191))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.VelVLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.VelVLayout.setContentsMargins(0, 0, 0, 0)
        self.VelVLayout.setObjectName("VelVLayout")
        self.VelLabel = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.VelLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.VelLabel.setObjectName("VelLabel")
        self.VelVLayout.addWidget(self.VelLabel)
        self.VelHLabel = QtWidgets.QHBoxLayout()
        self.VelHLabel.setObjectName("VelHLabel")
        self.U_VEL_Label = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.U_VEL_Label.setObjectName("U_VEL_Label")
        self.VelHLabel.addWidget(self.U_VEL_Label)
        self.V_VEL_Label = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.V_VEL_Label.setObjectName("V_VEL_Label")
        self.VelHLabel.addWidget(self.V_VEL_Label)
        self.W_VEL_Label = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.W_VEL_Label.setObjectName("W_VEL_Label")
        self.VelHLabel.addWidget(self.W_VEL_Label)
        self.VelVLayout.addLayout(self.VelHLabel)
        self.Vel_DISP = QtWidgets.QHBoxLayout()
        self.Vel_DISP.setObjectName("Vel_DISP")
        self.U_Vel_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_5)
        self.U_Vel_DISP.setObjectName("U_Vel_DISP")
        self.Vel_DISP.addWidget(self.U_Vel_DISP)
        self.V_Vel_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_5)
        self.V_Vel_DISP.setObjectName("V_Vel_DISP")
        self.Vel_DISP.addWidget(self.V_Vel_DISP)
        self.W_Vel_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_5)
        self.W_Vel_DISP.setObjectName("W_Vel_DISP")
        self.Vel_DISP.addWidget(self.W_Vel_DISP)
        self.VelVLayout.addLayout(self.Vel_DISP)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(660, 260, 161, 91))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.FlightTimeVLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.FlightTimeVLayout.setContentsMargins(0, 0, 0, 0)
        self.FlightTimeVLayout.setObjectName("FlightTimeVLayout")
        self.FlightTimeLabel = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.FlightTimeLabel.setObjectName("FlightTimeLabel")
        self.FlightTimeVLayout.addWidget(self.FlightTimeLabel)
        self.FlightTimeHLabel = QtWidgets.QHBoxLayout()
        self.FlightTimeHLabel.setObjectName("FlightTimeHLabel")
        self.Min_Label = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.Min_Label.setObjectName("Min_Label")
        self.FlightTimeHLabel.addWidget(self.Min_Label)
        self.Sec_Label = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.Sec_Label.setObjectName("Sec_Label")
        self.FlightTimeHLabel.addWidget(self.Sec_Label)
        self.FlightTimeVLayout.addLayout(self.FlightTimeHLabel)
        self.FlightTime_DISP = QtWidgets.QHBoxLayout()
        self.FlightTime_DISP.setObjectName("FlightTime_DISP")
        self.Min_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_6)
        self.Min_DISP.setObjectName("Min_DISP")
        self.FlightTime_DISP.addWidget(self.Min_DISP)
        self.Sec_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_6)
        self.Sec_DISP.setObjectName("Sec_DISP")
        self.FlightTime_DISP.addWidget(self.Sec_DISP)
        self.FlightTimeVLayout.addLayout(self.FlightTime_DISP)
        self.Logging = QtWidgets.QTextBrowser(self.AutonomousFlightMode_Tab)
        self.Logging.setGeometry(QtCore.QRect(1040, 90, 291, 371))
        self.Logging.setObjectName("Logging")
        self.FlightLogTitle = QtWidgets.QLabel(self.AutonomousFlightMode_Tab)
        self.FlightLogTitle.setGeometry(QtCore.QRect(1060, 20, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.FlightLogTitle.setFont(font)
        self.FlightLogTitle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.FlightLogTitle.setObjectName("FlightLogTitle")
        self.verticalLayoutWidget_15 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.verticalLayoutWidget_15.setGeometry(QtCore.QRect(30, 560, 421, 191))
        self.verticalLayoutWidget_15.setObjectName("verticalLayoutWidget_15")
        self.DesiredFlightLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_15)
        self.DesiredFlightLayout.setContentsMargins(0, 0, 0, 0)
        self.DesiredFlightLayout.setObjectName("DesiredFlightLayout")
        self.DesiredFlightCoordinates = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.DesiredFlightCoordinates.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.DesiredFlightCoordinates.setObjectName("DesiredFlightCoordinates")
        self.DesiredFlightLayout.addWidget(self.DesiredFlightCoordinates)
        self.FlightHLayout = QtWidgets.QHBoxLayout()
        self.FlightHLayout.setObjectName("FlightHLayout")
        self.XLabel1 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.XLabel1.setObjectName("XLabel1")
        self.FlightHLayout.addWidget(self.XLabel1)
        self.YLabel1 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.YLabel1.setObjectName("YLabel1")
        self.FlightHLayout.addWidget(self.YLabel1)
        self.ZLabel1 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.ZLabel1.setObjectName("ZLabel1")
        self.FlightHLayout.addWidget(self.ZLabel1)
        self.ZLabel1_3 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.ZLabel1_3.setObjectName("ZLabel1_3")
        self.FlightHLayout.addWidget(self.ZLabel1_3)
        self.DesiredFlightLayout.addLayout(self.FlightHLayout)
        self.FlightHLayout1 = QtWidgets.QHBoxLayout()
        self.FlightHLayout1.setObjectName("FlightHLayout1")
        self.XPositionUAV = QtWidgets.QLineEdit(self.verticalLayoutWidget_15)
        self.XPositionUAV.setText("")
        self.XPositionUAV.setObjectName("XPositionUAV")
        self.FlightHLayout1.addWidget(self.XPositionUAV)
        self.YPositionUAV = QtWidgets.QLineEdit(self.verticalLayoutWidget_15)
        self.YPositionUAV.setObjectName("YPositionUAV")
        self.FlightHLayout1.addWidget(self.YPositionUAV)
        self.ZPositionUAV = QtWidgets.QLineEdit(self.verticalLayoutWidget_15)
        self.ZPositionUAV.setObjectName("ZPositionUAV")
        self.FlightHLayout1.addWidget(self.ZPositionUAV)
        self.YAWUAV = QtWidgets.QLineEdit(self.verticalLayoutWidget_15)
        self.YAWUAV.setObjectName("YAWUAV")
        self.FlightHLayout1.addWidget(self.YAWUAV)
        self.DesiredFlightLayout.addLayout(self.FlightHLayout1)
        self.GetCurrentPositionUAV = QtWidgets.QPushButton(self.AutonomousFlightMode_Tab)
        self.GetCurrentPositionUAV.setGeometry(QtCore.QRect(30, 760, 201, 31))
        self.GetCurrentPositionUAV.setObjectName("GetCurrentPositionUAV")
        self.EmergencyStop = QtWidgets.QPushButton(self.AutonomousFlightMode_Tab)
        self.EmergencyStop.setEnabled(False)
        self.EmergencyStop.setGeometry(QtCore.QRect(970, 710, 351, 81))
        self.EmergencyStop.setObjectName("EmergencyStop")
        self.SendPositionUAV = QtWidgets.QPushButton(self.AutonomousFlightMode_Tab)
        self.SendPositionUAV.setGeometry(QtCore.QRect(250, 760, 201, 31))
        self.SendPositionUAV.setObjectName("SendPositionUAV")
        self.verticalLayoutWidget_14 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.verticalLayoutWidget_14.setGeometry(QtCore.QRect(350, 80, 291, 181))
        self.verticalLayoutWidget_14.setObjectName("verticalLayoutWidget_14")
        self.GPSDataLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_14)
        self.GPSDataLayout_3.setContentsMargins(0, 0, 0, 0)
        self.GPSDataLayout_3.setObjectName("GPSDataLayout_3")
        self.GPSLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.GPSLabel_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.GPSLabel_2.setObjectName("GPSLabel_2")
        self.GPSDataLayout_3.addWidget(self.GPSLabel_2)
        self.GPSHLayout_2 = QtWidgets.QHBoxLayout()
        self.GPSHLayout_2.setObjectName("GPSHLayout_2")
        self.LatLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.LatLabel_2.setObjectName("LatLabel_2")
        self.GPSHLayout_2.addWidget(self.LatLabel_2)
        self.LongLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.LongLabel_2.setObjectName("LongLabel_2")
        self.GPSHLayout_2.addWidget(self.LongLabel_2)
        self.AltLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.AltLabel_2.setObjectName("AltLabel_2")
        self.GPSHLayout_2.addWidget(self.AltLabel_2)
        self.GPSDataLayout_3.addLayout(self.GPSHLayout_2)
        self.GPS_DISP_2 = QtWidgets.QHBoxLayout()
        self.GPS_DISP_2.setObjectName("GPS_DISP_2")
        self.RelX_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_14)
        self.RelX_DISP.setObjectName("RelX_DISP")
        self.GPS_DISP_2.addWidget(self.RelX_DISP)
        self.RelY_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_14)
        self.RelY_DISP.setObjectName("RelY_DISP")
        self.GPS_DISP_2.addWidget(self.RelY_DISP)
        self.AGL_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_14)
        self.AGL_DISP.setObjectName("AGL_DISP")
        self.GPS_DISP_2.addWidget(self.AGL_DISP)
        self.GPSDataLayout_3.addLayout(self.GPS_DISP_2)
        self.AutonomousTitle_2 = QtWidgets.QLabel(self.AutonomousFlightMode_Tab)
        self.AutonomousTitle_2.setGeometry(QtCore.QRect(30, 490, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.AutonomousTitle_2.setFont(font)
        self.AutonomousTitle_2.setObjectName("AutonomousTitle_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(660, 170, 161, 77))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.BatLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.BatLayout.setContentsMargins(0, 0, 0, 0)
        self.BatLayout.setObjectName("BatLayout")
        self.BatInd = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.BatInd.setProperty("value", 20)
        self.BatInd.setTextVisible(False)
        self.BatInd.setObjectName("BatInd")
        self.BatLayout.addWidget(self.BatInd, 1, 0, 1, 2)
        self.Voltage_Label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Voltage_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Voltage_Label.setObjectName("Voltage_Label")
        self.BatLayout.addWidget(self.Voltage_Label, 0, 0, 1, 1)
        self.VOLT_DISP = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.VOLT_DISP.setObjectName("VOLT_DISP")
        self.BatLayout.addWidget(self.VOLT_DISP, 0, 1, 1, 1)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(840, 170, 171, 80))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.StateConnected = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.StateConnected.setStyleSheet("color : red")
        self.StateConnected.setFrameShape(QtWidgets.QFrame.Box)
        self.StateConnected.setFrameShadow(QtWidgets.QFrame.Plain)
        self.StateConnected.setAlignment(QtCore.Qt.AlignCenter)
        self.StateConnected.setObjectName("StateConnected")
        self.verticalLayout.addWidget(self.StateConnected)
        self.StateARM = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.StateARM.setStyleSheet("color : green")
        self.StateARM.setFrameShape(QtWidgets.QFrame.Box)
        self.StateARM.setFrameShadow(QtWidgets.QFrame.Plain)
        self.StateARM.setAlignment(QtCore.Qt.AlignCenter)
        self.StateARM.setObjectName("StateARM")
        self.verticalLayout.addWidget(self.StateARM)
        self.StateMode = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.StateMode.setStyleSheet("")
        self.StateMode.setFrameShape(QtWidgets.QFrame.Box)
        self.StateMode.setFrameShadow(QtWidgets.QFrame.Plain)
        self.StateMode.setAlignment(QtCore.Qt.AlignCenter)
        self.StateMode.setObjectName("StateMode")
        self.verticalLayout.addWidget(self.StateMode)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(970, 560, 351, 141))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.TakeoffHeight = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TakeoffHeight.sizePolicy().hasHeightForWidth())
        self.TakeoffHeight.setSizePolicy(sizePolicy)
        self.TakeoffHeight.setObjectName("TakeoffHeight")
        self.gridLayout.addWidget(self.TakeoffHeight, 3, 1, 1, 1)
        self.DISARM = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.DISARM.setEnabled(False)
        self.DISARM.setObjectName("DISARM")
        self.gridLayout.addWidget(self.DISARM, 2, 1, 1, 1)
        self.SimulationMode = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.SimulationMode.setChecked(False)
        self.SimulationMode.setObjectName("SimulationMode")
        self.gridLayout.addWidget(self.SimulationMode, 0, 0, 1, 1)
        self.Land = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.Land.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Land.sizePolicy().hasHeightForWidth())
        self.Land.setSizePolicy(sizePolicy)
        self.Land.setObjectName("Land")
        self.gridLayout.addWidget(self.Land, 4, 0, 1, 2)
        self.Takeoff = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.Takeoff.setEnabled(False)
        self.Takeoff.setObjectName("Takeoff")
        self.gridLayout.addWidget(self.Takeoff, 3, 0, 1, 1)
        self.ARM = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ARM.setEnabled(False)
        self.ARM.setObjectName("ARM")
        self.gridLayout.addWidget(self.ARM, 2, 0, 1, 1)
        self.OFFBOARD = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.OFFBOARD.setEnabled(False)
        self.OFFBOARD.setObjectName("OFFBOARD")
        self.gridLayout.addWidget(self.OFFBOARD, 5, 0, 1, 1)
        self.POSCTL = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.POSCTL.setEnabled(False)
        self.POSCTL.setObjectName("POSCTL")
        self.gridLayout.addWidget(self.POSCTL, 5, 1, 1, 1)
        self.StateSimulation = QtWidgets.QLabel(self.AutonomousFlightMode_Tab)
        self.StateSimulation.setGeometry(QtCore.QRect(660, 80, 351, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.StateSimulation.setFont(font)
        self.StateSimulation.setStyleSheet("color: red")
        self.StateSimulation.setFrameShape(QtWidgets.QFrame.Box)
        self.StateSimulation.setFrameShadow(QtWidgets.QFrame.Plain)
        self.StateSimulation.setAlignment(QtCore.Qt.AlignCenter)
        self.StateSimulation.setObjectName("StateSimulation")
        self.verticalLayoutWidget_19 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.verticalLayoutWidget_19.setGeometry(QtCore.QRect(840, 270, 181, 81))
        self.verticalLayoutWidget_19.setObjectName("verticalLayoutWidget_19")
        self.GPSDataLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_19)
        self.GPSDataLayout_4.setContentsMargins(0, 0, 0, 0)
        self.GPSDataLayout_4.setObjectName("GPSDataLayout_4")
        self.GPSLabel_5 = QtWidgets.QLabel(self.verticalLayoutWidget_19)
        self.GPSLabel_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.GPSLabel_5.setObjectName("GPSLabel_5")
        self.GPSDataLayout_4.addWidget(self.GPSLabel_5)
        self.GPS_DISP_3 = QtWidgets.QHBoxLayout()
        self.GPS_DISP_3.setObjectName("GPS_DISP_3")
        self.Geofence_X = QtWidgets.QLCDNumber(self.verticalLayoutWidget_19)
        self.Geofence_X.setDigitCount(4)
        self.Geofence_X.setObjectName("Geofence_X")
        self.GPS_DISP_3.addWidget(self.Geofence_X)
        self.Geofence_Y = QtWidgets.QLCDNumber(self.verticalLayoutWidget_19)
        self.Geofence_Y.setDigitCount(4)
        self.Geofence_Y.setObjectName("Geofence_Y")
        self.GPS_DISP_3.addWidget(self.Geofence_Y)
        self.Geofence_Z = QtWidgets.QLCDNumber(self.verticalLayoutWidget_19)
        self.Geofence_Z.setDigitCount(4)
        self.Geofence_Z.setObjectName("Geofence_Z")
        self.GPS_DISP_3.addWidget(self.Geofence_Z)
        self.GPSDataLayout_4.addLayout(self.GPS_DISP_3)
        self.verticalLayoutWidget_20 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.verticalLayoutWidget_20.setGeometry(QtCore.QRect(660, 370, 241, 91))
        self.verticalLayoutWidget_20.setObjectName("verticalLayoutWidget_20")
        self.GPSDataLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_20)
        self.GPSDataLayout_6.setContentsMargins(0, 0, 0, 0)
        self.GPSDataLayout_6.setObjectName("GPSDataLayout_6")
        self.GPSLabel_7 = QtWidgets.QLabel(self.verticalLayoutWidget_20)
        self.GPSLabel_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.GPSLabel_7.setObjectName("GPSLabel_7")
        self.GPSDataLayout_6.addWidget(self.GPSLabel_7)
        self.GPS_DISP_6 = QtWidgets.QHBoxLayout()
        self.GPS_DISP_6.setObjectName("GPS_DISP_6")
        self.TargROLL_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_20)
        self.TargROLL_DISP.setObjectName("TargROLL_DISP")
        self.GPS_DISP_6.addWidget(self.TargROLL_DISP)
        self.TargPITCH_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_20)
        self.TargPITCH_DISP.setObjectName("TargPITCH_DISP")
        self.GPS_DISP_6.addWidget(self.TargPITCH_DISP)
        self.TargYAW_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_20)
        self.TargYAW_DISP.setDigitCount(6)
        self.TargYAW_DISP.setObjectName("TargYAW_DISP")
        self.GPS_DISP_6.addWidget(self.TargYAW_DISP)
        self.GPSDataLayout_6.addLayout(self.GPS_DISP_6)
        self.verticalLayoutWidget_21 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.verticalLayoutWidget_21.setGeometry(QtCore.QRect(910, 370, 101, 91))
        self.verticalLayoutWidget_21.setObjectName("verticalLayoutWidget_21")
        self.GPSDataLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_21)
        self.GPSDataLayout_7.setContentsMargins(0, 0, 0, 0)
        self.GPSDataLayout_7.setObjectName("GPSDataLayout_7")
        self.GPSLabel_9 = QtWidgets.QLabel(self.verticalLayoutWidget_21)
        self.GPSLabel_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.GPSLabel_9.setObjectName("GPSLabel_9")
        self.GPSDataLayout_7.addWidget(self.GPSLabel_9)
        self.GPS_DISP_7 = QtWidgets.QHBoxLayout()
        self.GPS_DISP_7.setObjectName("GPS_DISP_7")
        self.TargTHRUST_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_21)
        self.TargTHRUST_DISP.setObjectName("TargTHRUST_DISP")
        self.GPS_DISP_7.addWidget(self.TargTHRUST_DISP)
        self.GPSDataLayout_7.addLayout(self.GPS_DISP_7)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(470, 690, 381, 101))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.HOLD = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HOLD.sizePolicy().hasHeightForWidth())
        self.HOLD.setSizePolicy(sizePolicy)
        self.HOLD.setIconSize(QtCore.QSize(16, 16))
        self.HOLD.setCheckable(False)
        self.HOLD.setAutoDefault(False)
        self.HOLD.setDefault(False)
        self.HOLD.setFlat(False)
        self.HOLD.setObjectName("HOLD")
        self.gridLayout_3.addWidget(self.HOLD, 1, 0, 1, 1)
        self.SetHome = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SetHome.sizePolicy().hasHeightForWidth())
        self.SetHome.setSizePolicy(sizePolicy)
        self.SetHome.setObjectName("SetHome")
        self.gridLayout_3.addWidget(self.SetHome, 1, 1, 1, 1)
        WaterSamplingGroundControlStation.addTab(self.AutonomousFlightMode_Tab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.titleWaterSampling = QtWidgets.QLabel(self.tab)
        self.titleWaterSampling.setGeometry(QtCore.QRect(30, 15, 481, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.titleWaterSampling.setFont(font)
        self.titleWaterSampling.setObjectName("titleWaterSampling")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(30, 90, 301, 181))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.GPSDataLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.GPSDataLayout_5.setContentsMargins(0, 0, 0, 0)
        self.GPSDataLayout_5.setObjectName("GPSDataLayout_5")
        self.lblRawEncoder = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.lblRawEncoder.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lblRawEncoder.setObjectName("lblRawEncoder")
        self.GPSDataLayout_5.addWidget(self.lblRawEncoder)
        self.GPSHLayout_3 = QtWidgets.QHBoxLayout()
        self.GPSHLayout_3.setObjectName("GPSHLayout_3")
        self.lblRawX = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.lblRawX.setObjectName("lblRawX")
        self.GPSHLayout_3.addWidget(self.lblRawX)
        self.lblRawY = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.lblRawY.setObjectName("lblRawY")
        self.GPSHLayout_3.addWidget(self.lblRawY)
        self.lblRawZ = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.lblRawZ.setObjectName("lblRawZ")
        self.GPSHLayout_3.addWidget(self.lblRawZ)
        self.GPSDataLayout_5.addLayout(self.GPSHLayout_3)
        self.GPS_DISP_5 = QtWidgets.QHBoxLayout()
        self.GPS_DISP_5.setObjectName("GPS_DISP_5")
        self.rawX_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_7)
        self.rawX_DISP.setObjectName("rawX_DISP")
        self.GPS_DISP_5.addWidget(self.rawX_DISP)
        self.rawY_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_7)
        self.rawY_DISP.setObjectName("rawY_DISP")
        self.GPS_DISP_5.addWidget(self.rawY_DISP)
        self.rawZ_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_7)
        self.rawZ_DISP.setObjectName("rawZ_DISP")
        self.GPS_DISP_5.addWidget(self.rawZ_DISP)
        self.GPSDataLayout_5.addLayout(self.GPS_DISP_5)
        self.verticalLayoutWidget_16 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_16.setGeometry(QtCore.QRect(30, 300, 301, 181))
        self.verticalLayoutWidget_16.setObjectName("verticalLayoutWidget_16")
        self.GPSDataLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_16)
        self.GPSDataLayout_8.setContentsMargins(0, 0, 0, 0)
        self.GPSDataLayout_8.setObjectName("GPSDataLayout_8")
        self.lblPosEst = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.lblPosEst.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lblPosEst.setObjectName("lblPosEst")
        self.GPSDataLayout_8.addWidget(self.lblPosEst)
        self.GPSHLayout_5 = QtWidgets.QHBoxLayout()
        self.GPSHLayout_5.setObjectName("GPSHLayout_5")
        self.lblPayloadX = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.lblPayloadX.setObjectName("lblPayloadX")
        self.GPSHLayout_5.addWidget(self.lblPayloadX)
        self.lblPayloadY = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.lblPayloadY.setObjectName("lblPayloadY")
        self.GPSHLayout_5.addWidget(self.lblPayloadY)
        self.lblPayloadZ = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.lblPayloadZ.setObjectName("lblPayloadZ")
        self.GPSHLayout_5.addWidget(self.lblPayloadZ)
        self.GPSDataLayout_8.addLayout(self.GPSHLayout_5)
        self.GPS_DISP_8 = QtWidgets.QHBoxLayout()
        self.GPS_DISP_8.setObjectName("GPS_DISP_8")
        self.PayloadX_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_16)
        self.PayloadX_DISP.setSmallDecimalPoint(False)
        self.PayloadX_DISP.setDigitCount(5)
        self.PayloadX_DISP.setObjectName("PayloadX_DISP")
        self.GPS_DISP_8.addWidget(self.PayloadX_DISP)
        self.PayloadY_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_16)
        self.PayloadY_DISP.setSmallDecimalPoint(False)
        self.PayloadY_DISP.setDigitCount(5)
        self.PayloadY_DISP.setObjectName("PayloadY_DISP")
        self.GPS_DISP_8.addWidget(self.PayloadY_DISP)
        self.PayloadZ_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_16)
        self.PayloadZ_DISP.setSmallDecimalPoint(False)
        self.PayloadZ_DISP.setDigitCount(5)
        self.PayloadZ_DISP.setObjectName("PayloadZ_DISP")
        self.GPS_DISP_8.addWidget(self.PayloadZ_DISP)
        self.GPSDataLayout_8.addLayout(self.GPS_DISP_8)
        self.titleControls = QtWidgets.QLabel(self.tab)
        self.titleControls.setGeometry(QtCore.QRect(-10, 520, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.titleControls.setFont(font)
        self.titleControls.setAlignment(QtCore.Qt.AlignCenter)
        self.titleControls.setObjectName("titleControls")
        self.btnGetCurLenght = QtWidgets.QPushButton(self.tab)
        self.btnGetCurLenght.setGeometry(QtCore.QRect(30, 750, 201, 31))
        self.btnGetCurLenght.setObjectName("btnGetCurLenght")
        self.btnSendCMD = QtWidgets.QPushButton(self.tab)
        self.btnSendCMD.setGeometry(QtCore.QRect(250, 750, 201, 31))
        self.btnSendCMD.setObjectName("btnSendCMD")
        self.verticalLayoutWidget_23 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_23.setGeometry(QtCore.QRect(350, 300, 301, 181))
        self.verticalLayoutWidget_23.setObjectName("verticalLayoutWidget_23")
        self.GPSDataLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_23)
        self.GPSDataLayout_9.setContentsMargins(0, 0, 0, 0)
        self.GPSDataLayout_9.setObjectName("GPSDataLayout_9")
        self.lblVelEst = QtWidgets.QLabel(self.verticalLayoutWidget_23)
        self.lblVelEst.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lblVelEst.setObjectName("lblVelEst")
        self.GPSDataLayout_9.addWidget(self.lblVelEst)
        self.GPSHLayout_6 = QtWidgets.QHBoxLayout()
        self.GPSHLayout_6.setObjectName("GPSHLayout_6")
        self.lblPayloadXDot = QtWidgets.QLabel(self.verticalLayoutWidget_23)
        self.lblPayloadXDot.setObjectName("lblPayloadXDot")
        self.GPSHLayout_6.addWidget(self.lblPayloadXDot)
        self.lblPayloadYDot = QtWidgets.QLabel(self.verticalLayoutWidget_23)
        self.lblPayloadYDot.setObjectName("lblPayloadYDot")
        self.GPSHLayout_6.addWidget(self.lblPayloadYDot)
        self.lblPayloadZDot = QtWidgets.QLabel(self.verticalLayoutWidget_23)
        self.lblPayloadZDot.setObjectName("lblPayloadZDot")
        self.GPSHLayout_6.addWidget(self.lblPayloadZDot)
        self.GPSDataLayout_9.addLayout(self.GPSHLayout_6)
        self.GPS_DISP_9 = QtWidgets.QHBoxLayout()
        self.GPS_DISP_9.setObjectName("GPS_DISP_9")
        self.PayloadXDot_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_23)
        self.PayloadXDot_DISP.setObjectName("PayloadXDot_DISP")
        self.GPS_DISP_9.addWidget(self.PayloadXDot_DISP)
        self.PayloadYDot_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_23)
        self.PayloadYDot_DISP.setObjectName("PayloadYDot_DISP")
        self.GPS_DISP_9.addWidget(self.PayloadYDot_DISP)
        self.PayloadZDot_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_23)
        self.PayloadZDot_DISP.setObjectName("PayloadZDot_DISP")
        self.GPS_DISP_9.addWidget(self.PayloadZDot_DISP)
        self.GPSDataLayout_9.addLayout(self.GPS_DISP_9)
        self.verticalLayoutWidget_24 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_24.setGeometry(QtCore.QRect(350, 90, 301, 181))
        self.verticalLayoutWidget_24.setObjectName("verticalLayoutWidget_24")
        self.GPSDataLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_24)
        self.GPSDataLayout_10.setContentsMargins(0, 0, 0, 0)
        self.GPSDataLayout_10.setObjectName("GPSDataLayout_10")
        self.lblRawEncoderSpd = QtWidgets.QLabel(self.verticalLayoutWidget_24)
        self.lblRawEncoderSpd.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lblRawEncoderSpd.setObjectName("lblRawEncoderSpd")
        self.GPSDataLayout_10.addWidget(self.lblRawEncoderSpd)
        self.GPSHLayout_7 = QtWidgets.QHBoxLayout()
        self.GPSHLayout_7.setObjectName("GPSHLayout_7")
        self.lblXDot = QtWidgets.QLabel(self.verticalLayoutWidget_24)
        self.lblXDot.setObjectName("lblXDot")
        self.GPSHLayout_7.addWidget(self.lblXDot)
        self.lblYDot = QtWidgets.QLabel(self.verticalLayoutWidget_24)
        self.lblYDot.setObjectName("lblYDot")
        self.GPSHLayout_7.addWidget(self.lblYDot)
        self.lblZDot = QtWidgets.QLabel(self.verticalLayoutWidget_24)
        self.lblZDot.setObjectName("lblZDot")
        self.GPSHLayout_7.addWidget(self.lblZDot)
        self.GPSDataLayout_10.addLayout(self.GPSHLayout_7)
        self.GPS_DISP_10 = QtWidgets.QHBoxLayout()
        self.GPS_DISP_10.setObjectName("GPS_DISP_10")
        self.rawXDot_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_24)
        self.rawXDot_DISP.setObjectName("rawXDot_DISP")
        self.GPS_DISP_10.addWidget(self.rawXDot_DISP)
        self.rawYDot_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_24)
        self.rawYDot_DISP.setObjectName("rawYDot_DISP")
        self.GPS_DISP_10.addWidget(self.rawYDot_DISP)
        self.rawZDot_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_24)
        self.rawZDot_DISP.setObjectName("rawZDot_DISP")
        self.GPS_DISP_10.addWidget(self.rawZDot_DISP)
        self.GPSDataLayout_10.addLayout(self.GPS_DISP_10)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(660, 90, 20, 391))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.btnDown = QtWidgets.QPushButton(self.tab)
        self.btnDown.setGeometry(QtCore.QRect(480, 750, 201, 31))
        self.btnDown.setObjectName("btnDown")
        self.btnUp = QtWidgets.QPushButton(self.tab)
        self.btnUp.setGeometry(QtCore.QRect(700, 750, 201, 31))
        self.btnUp.setObjectName("btnUp")
        self.titleCableLog = QtWidgets.QLabel(self.tab)
        self.titleCableLog.setGeometry(QtCore.QRect(1060, 30, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.titleCableLog.setFont(font)
        self.titleCableLog.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.titleCableLog.setObjectName("titleCableLog")
        self.Logging_3 = QtWidgets.QTextBrowser(self.tab)
        self.Logging_3.setGeometry(QtCore.QRect(1030, 90, 271, 391))
        self.Logging_3.setObjectName("Logging_3")
        self.verticalLayoutWidget_26 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_26.setGeometry(QtCore.QRect(710, 90, 161, 91))
        self.verticalLayoutWidget_26.setObjectName("verticalLayoutWidget_26")
        self.FlightTimeVLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_26)
        self.FlightTimeVLayout_2.setContentsMargins(0, 0, 0, 0)
        self.FlightTimeVLayout_2.setObjectName("FlightTimeVLayout_2")
        self.FlightTimeLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget_26)
        self.FlightTimeLabel_2.setObjectName("FlightTimeLabel_2")
        self.FlightTimeVLayout_2.addWidget(self.FlightTimeLabel_2)
        self.FlightTimeHLabel_2 = QtWidgets.QHBoxLayout()
        self.FlightTimeHLabel_2.setObjectName("FlightTimeHLabel_2")
        self.Min_Label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_26)
        self.Min_Label_2.setObjectName("Min_Label_2")
        self.FlightTimeHLabel_2.addWidget(self.Min_Label_2)
        self.Sec_Label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_26)
        self.Sec_Label_2.setObjectName("Sec_Label_2")
        self.FlightTimeHLabel_2.addWidget(self.Sec_Label_2)
        self.FlightTimeVLayout_2.addLayout(self.FlightTimeHLabel_2)
        self.FlightTime_DISP_2 = QtWidgets.QHBoxLayout()
        self.FlightTime_DISP_2.setObjectName("FlightTime_DISP_2")
        self.Min_DISP_2 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_26)
        self.Min_DISP_2.setObjectName("Min_DISP_2")
        self.FlightTime_DISP_2.addWidget(self.Min_DISP_2)
        self.Sec_DISP_2 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_26)
        self.Sec_DISP_2.setObjectName("Sec_DISP_2")
        self.FlightTime_DISP_2.addWidget(self.Sec_DISP_2)
        self.FlightTimeVLayout_2.addLayout(self.FlightTime_DISP_2)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(30, 580, 421, 171))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.speed_CMD = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speed_CMD.sizePolicy().hasHeightForWidth())
        self.speed_CMD.setSizePolicy(sizePolicy)
        self.speed_CMD.setMinimumSize(QtCore.QSize(0, 0))
        self.speed_CMD.setText("")
        self.speed_CMD.setObjectName("speed_CMD")
        self.gridLayout_2.addWidget(self.speed_CMD, 2, 1, 1, 1)
        self.lblDesiredCableLength = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDesiredCableLength.sizePolicy().hasHeightForWidth())
        self.lblDesiredCableLength.setSizePolicy(sizePolicy)
        self.lblDesiredCableLength.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lblDesiredCableLength.setObjectName("lblDesiredCableLength")
        self.gridLayout_2.addWidget(self.lblDesiredCableLength, 0, 0, 1, 2)
        self.lblAmplitude_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAmplitude_2.sizePolicy().hasHeightForWidth())
        self.lblAmplitude_2.setSizePolicy(sizePolicy)
        self.lblAmplitude_2.setObjectName("lblAmplitude_2")
        self.gridLayout_2.addWidget(self.lblAmplitude_2, 1, 0, 1, 1)
        self.lblSpeed_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSpeed_2.sizePolicy().hasHeightForWidth())
        self.lblSpeed_2.setSizePolicy(sizePolicy)
        self.lblSpeed_2.setObjectName("lblSpeed_2")
        self.gridLayout_2.addWidget(self.lblSpeed_2, 1, 1, 1, 1)
        self.length_CMD = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.length_CMD.sizePolicy().hasHeightForWidth())
        self.length_CMD.setSizePolicy(sizePolicy)
        self.length_CMD.setMinimumSize(QtCore.QSize(0, 0))
        self.length_CMD.setText("")
        self.length_CMD.setObjectName("length_CMD")
        self.gridLayout_2.addWidget(self.length_CMD, 2, 0, 1, 1)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(480, 580, 421, 191))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lblStepperMotorControl = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblStepperMotorControl.sizePolicy().hasHeightForWidth())
        self.lblStepperMotorControl.setSizePolicy(sizePolicy)
        self.lblStepperMotorControl.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lblStepperMotorControl.setObjectName("lblStepperMotorControl")
        self.gridLayout_4.addWidget(self.lblStepperMotorControl, 0, 0, 1, 2)
        self.increment_CMD = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.increment_CMD.sizePolicy().hasHeightForWidth())
        self.increment_CMD.setSizePolicy(sizePolicy)
        self.increment_CMD.setMinimumSize(QtCore.QSize(0, 0))
        self.increment_CMD.setText("")
        self.increment_CMD.setObjectName("increment_CMD")
        self.gridLayout_4.addWidget(self.increment_CMD, 1, 1, 1, 1)
        self.lblIncrement = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.lblIncrement.setObjectName("lblIncrement")
        self.gridLayout_4.addWidget(self.lblIncrement, 1, 0, 1, 1)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(930, 580, 371, 171))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lblSpeed = QtWidgets.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSpeed.sizePolicy().hasHeightForWidth())
        self.lblSpeed.setSizePolicy(sizePolicy)
        self.lblSpeed.setObjectName("lblSpeed")
        self.gridLayout_5.addWidget(self.lblSpeed, 1, 1, 1, 1)
        self.lblTesting = QtWidgets.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTesting.sizePolicy().hasHeightForWidth())
        self.lblTesting.setSizePolicy(sizePolicy)
        self.lblTesting.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lblTesting.setObjectName("lblTesting")
        self.gridLayout_5.addWidget(self.lblTesting, 0, 0, 1, 2)
        self.test_frequency_CMD = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_frequency_CMD.sizePolicy().hasHeightForWidth())
        self.test_frequency_CMD.setSizePolicy(sizePolicy)
        self.test_frequency_CMD.setMinimumSize(QtCore.QSize(0, 0))
        self.test_frequency_CMD.setText("")
        self.test_frequency_CMD.setObjectName("test_frequency_CMD")
        self.gridLayout_5.addWidget(self.test_frequency_CMD, 2, 1, 1, 1)
        self.lblAmplitude = QtWidgets.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAmplitude.sizePolicy().hasHeightForWidth())
        self.lblAmplitude.setSizePolicy(sizePolicy)
        self.lblAmplitude.setObjectName("lblAmplitude")
        self.gridLayout_5.addWidget(self.lblAmplitude, 1, 0, 1, 1)
        self.test_amp_CMD = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_amp_CMD.sizePolicy().hasHeightForWidth())
        self.test_amp_CMD.setSizePolicy(sizePolicy)
        self.test_amp_CMD.setMinimumSize(QtCore.QSize(0, 0))
        self.test_amp_CMD.setText("")
        self.test_amp_CMD.setObjectName("test_amp_CMD")
        self.gridLayout_5.addWidget(self.test_amp_CMD, 2, 0, 1, 1)
        self.btnStartTest = QtWidgets.QPushButton(self.tab)
        self.btnStartTest.setGeometry(QtCore.QRect(930, 750, 181, 31))
        self.btnStartTest.setObjectName("btnStartTest")
        self.btnStopTest = QtWidgets.QPushButton(self.tab)
        self.btnStopTest.setGeometry(QtCore.QRect(1120, 750, 181, 31))
        self.btnStopTest.setObjectName("btnStopTest")
        WaterSamplingGroundControlStation.addTab(self.tab, "")
        self.ManualFlightManagment_Tab = QtWidgets.QWidget()
        self.ManualFlightManagment_Tab.setObjectName("ManualFlightManagment_Tab")
        self.ManualFlightTitle = QtWidgets.QLabel(self.ManualFlightManagment_Tab)
        self.ManualFlightTitle.setGeometry(QtCore.QRect(10, 0, 321, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.ManualFlightTitle.setFont(font)
        self.ManualFlightTitle.setObjectName("ManualFlightTitle")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.ManualFlightManagment_Tab)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(770, 10, 160, 110))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.FlightTimeVLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.FlightTimeVLayout_4.setContentsMargins(0, 0, 0, 0)
        self.FlightTimeVLayout_4.setObjectName("FlightTimeVLayout_4")
        self.FlightTimeLabel_4 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.FlightTimeLabel_4.setObjectName("FlightTimeLabel_4")
        self.FlightTimeVLayout_4.addWidget(self.FlightTimeLabel_4)
        self.FlightTimeHLabel_4 = QtWidgets.QHBoxLayout()
        self.FlightTimeHLabel_4.setObjectName("FlightTimeHLabel_4")
        self.Min_Label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.Min_Label_4.setObjectName("Min_Label_4")
        self.FlightTimeHLabel_4.addWidget(self.Min_Label_4)
        self.Sec_Label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.Sec_Label_4.setObjectName("Sec_Label_4")
        self.FlightTimeHLabel_4.addWidget(self.Sec_Label_4)
        self.FlightTimeVLayout_4.addLayout(self.FlightTimeHLabel_4)
        self.FlightTime_DISP_4 = QtWidgets.QHBoxLayout()
        self.FlightTime_DISP_4.setObjectName("FlightTime_DISP_4")
        self.Min_DISP_4 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_8)
        self.Min_DISP_4.setObjectName("Min_DISP_4")
        self.FlightTime_DISP_4.addWidget(self.Min_DISP_4)
        self.Sec_DISP_4 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_8)
        self.Sec_DISP_4.setObjectName("Sec_DISP_4")
        self.FlightTime_DISP_4.addWidget(self.Sec_DISP_4)
        self.FlightTimeVLayout_4.addLayout(self.FlightTime_DISP_4)
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.ManualFlightManagment_Tab)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(10, 100, 301, 181))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.GPSDataLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.GPSDataLayout_2.setContentsMargins(0, 0, 0, 0)
        self.GPSDataLayout_2.setObjectName("GPSDataLayout_2")
        self.GPSLabel_4 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.GPSLabel_4.setObjectName("GPSLabel_4")
        self.GPSDataLayout_2.addWidget(self.GPSLabel_4)
        self.GPSHLayout_4 = QtWidgets.QHBoxLayout()
        self.GPSHLayout_4.setObjectName("GPSHLayout_4")
        self.LatLabel_4 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.LatLabel_4.setObjectName("LatLabel_4")
        self.GPSHLayout_4.addWidget(self.LatLabel_4)
        self.LongLabel_4 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.LongLabel_4.setObjectName("LongLabel_4")
        self.GPSHLayout_4.addWidget(self.LongLabel_4)
        self.AltLabel_4 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.AltLabel_4.setObjectName("AltLabel_4")
        self.GPSHLayout_4.addWidget(self.AltLabel_4)
        self.GPSDataLayout_2.addLayout(self.GPSHLayout_4)
        self.GPS_DISP_4 = QtWidgets.QHBoxLayout()
        self.GPS_DISP_4.setObjectName("GPS_DISP_4")
        self.LatGPS_DISP_4 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_9)
        self.LatGPS_DISP_4.setObjectName("LatGPS_DISP_4")
        self.GPS_DISP_4.addWidget(self.LatGPS_DISP_4)
        self.LongGPS_DISP_4 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_9)
        self.LongGPS_DISP_4.setObjectName("LongGPS_DISP_4")
        self.GPS_DISP_4.addWidget(self.LongGPS_DISP_4)
        self.AltGPS_DISP_4 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_9)
        self.AltGPS_DISP_4.setObjectName("AltGPS_DISP_4")
        self.GPS_DISP_4.addWidget(self.AltGPS_DISP_4)
        self.GPSDataLayout_2.addLayout(self.GPS_DISP_4)
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.ManualFlightManagment_Tab)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(410, 10, 160, 80))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.BatLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.BatLayout_2.setContentsMargins(0, 0, 0, 0)
        self.BatLayout_2.setObjectName("BatLayout_2")
        self.BatLabel_4 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        self.BatLabel_4.setObjectName("BatLabel_4")
        self.BatLayout_2.addWidget(self.BatLabel_4)
        self.BatInd_4 = QtWidgets.QProgressBar(self.verticalLayoutWidget_10)
        self.BatInd_4.setProperty("value", 24)
        self.BatInd_4.setObjectName("BatInd_4")
        self.BatLayout_2.addWidget(self.BatInd_4)
        self.FlightLogTitle_2 = QtWidgets.QLabel(self.ManualFlightManagment_Tab)
        self.FlightLogTitle_2.setGeometry(QtCore.QRect(740, 250, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.FlightLogTitle_2.setFont(font)
        self.FlightLogTitle_2.setObjectName("FlightLogTitle_2")
        self.Logging_2 = QtWidgets.QTextBrowser(self.ManualFlightManagment_Tab)
        self.Logging_2.setGeometry(QtCore.QRect(620, 300, 321, 481))
        self.Logging_2.setObjectName("Logging_2")
        self.GetCurrentPositionUAV_2 = QtWidgets.QPushButton(self.ManualFlightManagment_Tab)
        self.GetCurrentPositionUAV_2.setGeometry(QtCore.QRect(10, 490, 141, 31))
        self.GetCurrentPositionUAV_2.setObjectName("GetCurrentPositionUAV_2")
        self.GetCurrentPositionPayload_2 = QtWidgets.QPushButton(self.ManualFlightManagment_Tab)
        self.GetCurrentPositionPayload_2.setGeometry(QtCore.QRect(10, 730, 141, 31))
        self.GetCurrentPositionPayload_2.setObjectName("GetCurrentPositionPayload_2")
        self.SendPositionPayload_2 = QtWidgets.QPushButton(self.ManualFlightManagment_Tab)
        self.SendPositionPayload_2.setGeometry(QtCore.QRect(170, 730, 141, 31))
        self.SendPositionPayload_2.setObjectName("SendPositionPayload_2")
        self.verticalLayoutWidget_17 = QtWidgets.QWidget(self.ManualFlightManagment_Tab)
        self.verticalLayoutWidget_17.setGeometry(QtCore.QRect(10, 300, 301, 181))
        self.verticalLayoutWidget_17.setObjectName("verticalLayoutWidget_17")
        self.DesiredFlightLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_17)
        self.DesiredFlightLayout_2.setContentsMargins(0, 0, 0, 0)
        self.DesiredFlightLayout_2.setObjectName("DesiredFlightLayout_2")
        self.DesiredFlightCoordinates_2 = QtWidgets.QLabel(self.verticalLayoutWidget_17)
        self.DesiredFlightCoordinates_2.setObjectName("DesiredFlightCoordinates_2")
        self.DesiredFlightLayout_2.addWidget(self.DesiredFlightCoordinates_2)
        self.FlightHLayout_2 = QtWidgets.QHBoxLayout()
        self.FlightHLayout_2.setObjectName("FlightHLayout_2")
        self.XLabel1_2 = QtWidgets.QLabel(self.verticalLayoutWidget_17)
        self.XLabel1_2.setObjectName("XLabel1_2")
        self.FlightHLayout_2.addWidget(self.XLabel1_2)
        self.YLabel1_2 = QtWidgets.QLabel(self.verticalLayoutWidget_17)
        self.YLabel1_2.setObjectName("YLabel1_2")
        self.FlightHLayout_2.addWidget(self.YLabel1_2)
        self.ZLabel1_2 = QtWidgets.QLabel(self.verticalLayoutWidget_17)
        self.ZLabel1_2.setObjectName("ZLabel1_2")
        self.FlightHLayout_2.addWidget(self.ZLabel1_2)
        self.WLabel1_2 = QtWidgets.QLabel(self.verticalLayoutWidget_17)
        self.WLabel1_2.setObjectName("WLabel1_2")
        self.FlightHLayout_2.addWidget(self.WLabel1_2)
        self.DesiredFlightLayout_2.addLayout(self.FlightHLayout_2)
        self.FlightHLayout1_2 = QtWidgets.QHBoxLayout()
        self.FlightHLayout1_2.setObjectName("FlightHLayout1_2")
        self.XPositionUAV_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_17)
        self.XPositionUAV_2.setObjectName("XPositionUAV_2")
        self.FlightHLayout1_2.addWidget(self.XPositionUAV_2)
        self.YPositionUAV_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_17)
        self.YPositionUAV_2.setObjectName("YPositionUAV_2")
        self.FlightHLayout1_2.addWidget(self.YPositionUAV_2)
        self.ZPositionUAV_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_17)
        self.ZPositionUAV_2.setObjectName("ZPositionUAV_2")
        self.FlightHLayout1_2.addWidget(self.ZPositionUAV_2)
        self.WPositionUAV_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_17)
        self.WPositionUAV_2.setObjectName("WPositionUAV_2")
        self.FlightHLayout1_2.addWidget(self.WPositionUAV_2)
        self.DesiredFlightLayout_2.addLayout(self.FlightHLayout1_2)
        self.SendPositionUAV_2 = QtWidgets.QPushButton(self.ManualFlightManagment_Tab)
        self.SendPositionUAV_2.setGeometry(QtCore.QRect(170, 490, 141, 31))
        self.SendPositionUAV_2.setObjectName("SendPositionUAV_2")
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.ManualFlightManagment_Tab)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(590, 10, 160, 80))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.FlightDistVLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.FlightDistVLayout_4.setContentsMargins(0, 0, 0, 0)
        self.FlightDistVLayout_4.setObjectName("FlightDistVLayout_4")
        self.FlightDistLabel_4 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        self.FlightDistLabel_4.setObjectName("FlightDistLabel_4")
        self.FlightDistVLayout_4.addWidget(self.FlightDistLabel_4)
        self.FlightDistHLayout_4 = QtWidgets.QHBoxLayout()
        self.FlightDistHLayout_4.setObjectName("FlightDistHLayout_4")
        self.Meters_DISP_4 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_11)
        self.Meters_DISP_4.setObjectName("Meters_DISP_4")
        self.FlightDistHLayout_4.addWidget(self.Meters_DISP_4)
        self.Meters_Label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        self.Meters_Label_4.setObjectName("Meters_Label_4")
        self.FlightDistHLayout_4.addWidget(self.Meters_Label_4)
        self.FlightDistVLayout_4.addLayout(self.FlightDistHLayout_4)
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self.ManualFlightManagment_Tab)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(330, 300, 281, 181))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.VelVLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.VelVLayout_4.setContentsMargins(0, 0, 0, 0)
        self.VelVLayout_4.setObjectName("VelVLayout_4")
        self.VelLabel_4 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        self.VelLabel_4.setObjectName("VelLabel_4")
        self.VelVLayout_4.addWidget(self.VelLabel_4)
        self.VelHLabel_4 = QtWidgets.QHBoxLayout()
        self.VelHLabel_4.setObjectName("VelHLabel_4")
        self.U_VEL_Label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        self.U_VEL_Label_4.setObjectName("U_VEL_Label_4")
        self.VelHLabel_4.addWidget(self.U_VEL_Label_4)
        self.V_VEL_Label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        self.V_VEL_Label_4.setObjectName("V_VEL_Label_4")
        self.VelHLabel_4.addWidget(self.V_VEL_Label_4)
        self.W_VEL_Label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        self.W_VEL_Label_4.setObjectName("W_VEL_Label_4")
        self.VelHLabel_4.addWidget(self.W_VEL_Label_4)
        self.VelVLayout_4.addLayout(self.VelHLabel_4)
        self.Vel_DISP_4 = QtWidgets.QHBoxLayout()
        self.Vel_DISP_4.setObjectName("Vel_DISP_4")
        self.U_Vel_DISP_4 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_12)
        self.U_Vel_DISP_4.setObjectName("U_Vel_DISP_4")
        self.Vel_DISP_4.addWidget(self.U_Vel_DISP_4)
        self.V_Vel_DISP_4 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_12)
        self.V_Vel_DISP_4.setObjectName("V_Vel_DISP_4")
        self.Vel_DISP_4.addWidget(self.V_Vel_DISP_4)
        self.W_Vel_DISP_4 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_12)
        self.W_Vel_DISP_4.setObjectName("W_Vel_DISP_4")
        self.Vel_DISP_4.addWidget(self.W_Vel_DISP_4)
        self.VelVLayout_4.addLayout(self.Vel_DISP_4)
        self.EmergencyStop_2 = QtWidgets.QPushButton(self.ManualFlightManagment_Tab)
        self.EmergencyStop_2.setGeometry(QtCore.QRect(620, 130, 311, 121))
        self.EmergencyStop_2.setObjectName("EmergencyStop_2")
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(self.ManualFlightManagment_Tab)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(330, 100, 281, 181))
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.IMULayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.IMULayout_2.setContentsMargins(0, 0, 0, 0)
        self.IMULayout_2.setObjectName("IMULayout_2")
        self.IMULabel_4 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.IMULabel_4.setObjectName("IMULabel_4")
        self.IMULayout_2.addWidget(self.IMULabel_4)
        self.IMUHLayout_2 = QtWidgets.QHBoxLayout()
        self.IMUHLayout_2.setObjectName("IMUHLayout_2")
        self.XLabel0_2 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.XLabel0_2.setObjectName("XLabel0_2")
        self.IMUHLayout_2.addWidget(self.XLabel0_2)
        self.YLabel0_2 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.YLabel0_2.setObjectName("YLabel0_2")
        self.IMUHLayout_2.addWidget(self.YLabel0_2)
        self.ZLabel0_2 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.ZLabel0_2.setObjectName("ZLabel0_2")
        self.IMUHLayout_2.addWidget(self.ZLabel0_2)
        self.WLabel0_2 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.WLabel0_2.setObjectName("WLabel0_2")
        self.IMUHLayout_2.addWidget(self.WLabel0_2)
        self.IMULayout_2.addLayout(self.IMUHLayout_2)
        self.IMU_DISP_2 = QtWidgets.QHBoxLayout()
        self.IMU_DISP_2.setObjectName("IMU_DISP_2")
        self.X_DISP_4 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_13)
        self.X_DISP_4.setObjectName("X_DISP_4")
        self.IMU_DISP_2.addWidget(self.X_DISP_4)
        self.Y_DISP_4 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_13)
        self.Y_DISP_4.setObjectName("Y_DISP_4")
        self.IMU_DISP_2.addWidget(self.Y_DISP_4)
        self.Z_DISP_4 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_13)
        self.Z_DISP_4.setObjectName("Z_DISP_4")
        self.IMU_DISP_2.addWidget(self.Z_DISP_4)
        self.W_DISP_4 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_13)
        self.W_DISP_4.setObjectName("W_DISP_4")
        self.IMU_DISP_2.addWidget(self.W_DISP_4)
        self.IMULayout_2.addLayout(self.IMU_DISP_2)
        self.verticalLayoutWidget_18 = QtWidgets.QWidget(self.ManualFlightManagment_Tab)
        self.verticalLayoutWidget_18.setGeometry(QtCore.QRect(10, 530, 301, 191))
        self.verticalLayoutWidget_18.setObjectName("verticalLayoutWidget_18")
        self.WaterSamplingLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_18)
        self.WaterSamplingLayout_2.setContentsMargins(0, 0, 0, 0)
        self.WaterSamplingLayout_2.setObjectName("WaterSamplingLayout_2")
        self.DesiredWaterSamplingPayloadCoordinates_2 = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        self.DesiredWaterSamplingPayloadCoordinates_2.setObjectName("DesiredWaterSamplingPayloadCoordinates_2")
        self.WaterSamplingLayout_2.addWidget(self.DesiredWaterSamplingPayloadCoordinates_2)
        self.WaterHLayout_2 = QtWidgets.QHBoxLayout()
        self.WaterHLayout_2.setObjectName("WaterHLayout_2")
        self.XLabel2_2 = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        self.XLabel2_2.setObjectName("XLabel2_2")
        self.WaterHLayout_2.addWidget(self.XLabel2_2)
        self.YLabel2_2 = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        self.YLabel2_2.setObjectName("YLabel2_2")
        self.WaterHLayout_2.addWidget(self.YLabel2_2)
        self.ZLabel2_2 = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        self.ZLabel2_2.setObjectName("ZLabel2_2")
        self.WaterHLayout_2.addWidget(self.ZLabel2_2)
        self.WLabel2_2 = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        self.WLabel2_2.setObjectName("WLabel2_2")
        self.WaterHLayout_2.addWidget(self.WLabel2_2)
        self.WaterSamplingLayout_2.addLayout(self.WaterHLayout_2)
        self.WaterHLayout1_2 = QtWidgets.QHBoxLayout()
        self.WaterHLayout1_2.setObjectName("WaterHLayout1_2")
        self.XPositionPayload_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_18)
        self.XPositionPayload_2.setObjectName("XPositionPayload_2")
        self.WaterHLayout1_2.addWidget(self.XPositionPayload_2)
        self.YPositionPayload_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_18)
        self.YPositionPayload_2.setObjectName("YPositionPayload_2")
        self.WaterHLayout1_2.addWidget(self.YPositionPayload_2)
        self.ZPositionPayload_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_18)
        self.ZPositionPayload_2.setObjectName("ZPositionPayload_2")
        self.WaterHLayout1_2.addWidget(self.ZPositionPayload_2)
        self.WPositionPayload_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_18)
        self.WPositionPayload_2.setObjectName("WPositionPayload_2")
        self.WaterHLayout1_2.addWidget(self.WPositionPayload_2)
        self.WaterSamplingLayout_2.addLayout(self.WaterHLayout1_2)
        WaterSamplingGroundControlStation.addTab(self.ManualFlightManagment_Tab, "")
        self.References_Tab = QtWidgets.QWidget()
        self.References_Tab.setObjectName("References_Tab")
        self.ReferencesTitle = QtWidgets.QLabel(self.References_Tab)
        self.ReferencesTitle.setGeometry(QtCore.QRect(20, 20, 151, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ReferencesTitle.setFont(font)
        self.ReferencesTitle.setObjectName("ReferencesTitle")
        self.ReferencesInfo = QtWidgets.QLabel(self.References_Tab)
        self.ReferencesInfo.setGeometry(QtCore.QRect(30, 80, 491, 661))
        self.ReferencesInfo.setWordWrap(True)
        self.ReferencesInfo.setObjectName("ReferencesInfo")
        WaterSamplingGroundControlStation.addTab(self.References_Tab, "")

        self.retranslateUi(WaterSamplingGroundControlStation)
        WaterSamplingGroundControlStation.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(WaterSamplingGroundControlStation)

    def retranslateUi(self, WaterSamplingGroundControlStation):
        _translate = QtCore.QCoreApplication.translate
        WaterSamplingGroundControlStation.setWindowTitle(_translate("WaterSamplingGroundControlStation", "TabWidget"))
        self.InitTitle.setText(_translate("WaterSamplingGroundControlStation", "UAV INITIALIZATION"))
        self.Welcome.setText(_translate("WaterSamplingGroundControlStation", "<html><head/><body><p>Welcome to the Water Sampling Ground Control Station! Here you will be able to set up, monitor and fly the UAV autonomously or manually. To fly, please start ROSCore, MAVROS and OFFBOARD for communication and control with UAV</p></body></html>"))
        self.ROSCoreInfo.setText(_translate("WaterSamplingGroundControlStation", "<html><head/><body><p>ROS Core </p><p>Roscore is a collection of nodes and programs that make up the pre-requisites of the robot operating system. You must have one and only one roscore running to be able to do any communication between nodes, and therefore communicate and fly the UAV [1]</p></body></html>"))
        self.StartROSCore.setText(_translate("WaterSamplingGroundControlStation", "Start ROS Core"))
        self.MAVROSInfo.setText(_translate("WaterSamplingGroundControlStation", "<html><head/><body><p>MAVROS</p><p>MAVROS is a package that provides communication drivers for various autopilots with the MAVLink protocol. It additionally provides the UDP MAVLink bridge for ground control stations such as QGroundControl. We harness the same communication to generate this ground control station.<br/></p></body></html>"))
        self.StartMAVROS.setText(_translate("WaterSamplingGroundControlStation", "Start MAVROS Communication"))
        self.OFFBOARDInfo.setText(_translate("WaterSamplingGroundControlStation", "<html><head/><body><p>OFFBOARD</p><p>Offboard mode is a function supported by all Pixhawk flight controllers except the 3DR Pixhawk1 [3]. It allows the vehicle to obey position, velocity, accleeration, attitude, altitude rates or thrust setpoints provided by an external source to the flight stack such as a companion computer. In this case we use Jetson Nano to run the flight controller and communicate the data over the MAVLink protocal. [4]</p></body></html>"))
        self.StartOffboard.setText(_translate("WaterSamplingGroundControlStation", "Start OFFBOARD MODE"))
        WaterSamplingGroundControlStation.setTabText(WaterSamplingGroundControlStation.indexOf(self.Initialization_Tab), _translate("WaterSamplingGroundControlStation", "Initilization"))
        self.AutonomousTitle.setText(_translate("WaterSamplingGroundControlStation", "Autonomous Flight"))
        self.GPSLabel.setText(_translate("WaterSamplingGroundControlStation", "Global Position"))
        self.LatLabel.setText(_translate("WaterSamplingGroundControlStation", "Lateral"))
        self.LongLabel.setText(_translate("WaterSamplingGroundControlStation", "Longitudinal"))
        self.AltLabel.setText(_translate("WaterSamplingGroundControlStation", "Altitude (MSL)"))
        self.IMULabel.setText(_translate("WaterSamplingGroundControlStation", "IMU (Orientation °)"))
        self.XLabel0.setText(_translate("WaterSamplingGroundControlStation", "Roll"))
        self.YLabel0.setText(_translate("WaterSamplingGroundControlStation", "Pitch"))
        self.ZLabel0.setText(_translate("WaterSamplingGroundControlStation", "Yaw"))
        self.VelLabel.setText(_translate("WaterSamplingGroundControlStation", "Velocity"))
        self.U_VEL_Label.setText(_translate("WaterSamplingGroundControlStation", "U"))
        self.V_VEL_Label.setText(_translate("WaterSamplingGroundControlStation", "V"))
        self.W_VEL_Label.setText(_translate("WaterSamplingGroundControlStation", "W"))
        self.FlightTimeLabel.setText(_translate("WaterSamplingGroundControlStation", "Flight Time"))
        self.Min_Label.setText(_translate("WaterSamplingGroundControlStation", "Min"))
        self.Sec_Label.setText(_translate("WaterSamplingGroundControlStation", "Secs"))
        self.FlightLogTitle.setText(_translate("WaterSamplingGroundControlStation", "Flight Log"))
        self.DesiredFlightCoordinates.setText(_translate("WaterSamplingGroundControlStation", "Desired Flight Coordinates"))
        self.XLabel1.setText(_translate("WaterSamplingGroundControlStation", "X"))
        self.YLabel1.setText(_translate("WaterSamplingGroundControlStation", "Y"))
        self.ZLabel1.setText(_translate("WaterSamplingGroundControlStation", "Z"))
        self.ZLabel1_3.setText(_translate("WaterSamplingGroundControlStation", "Yaw"))
        self.GetCurrentPositionUAV.setText(_translate("WaterSamplingGroundControlStation", "Get Current Position"))
        self.EmergencyStop.setText(_translate("WaterSamplingGroundControlStation", "Emergency Stop"))
        self.SendPositionUAV.setText(_translate("WaterSamplingGroundControlStation", "Send New Position"))
        self.SendPositionUAV.setShortcut(_translate("WaterSamplingGroundControlStation", "Return"))
        self.GPSLabel_2.setText(_translate("WaterSamplingGroundControlStation", "Relative Position"))
        self.LatLabel_2.setText(_translate("WaterSamplingGroundControlStation", "X"))
        self.LongLabel_2.setText(_translate("WaterSamplingGroundControlStation", "Y"))
        self.AltLabel_2.setText(_translate("WaterSamplingGroundControlStation", "Altitude (AGL)"))
        self.AutonomousTitle_2.setText(_translate("WaterSamplingGroundControlStation", "Controls"))
        self.Voltage_Label.setText(_translate("WaterSamplingGroundControlStation", "Voltage:"))
        self.StateConnected.setText(_translate("WaterSamplingGroundControlStation", "DISCONNECTED"))
        self.StateARM.setText(_translate("WaterSamplingGroundControlStation", "DISARMED"))
        self.StateMode.setText(_translate("WaterSamplingGroundControlStation", "MODE"))
        self.TakeoffHeight.setText(_translate("WaterSamplingGroundControlStation", "2.0"))
        self.DISARM.setText(_translate("WaterSamplingGroundControlStation", "Disarm"))
        self.SimulationMode.setText(_translate("WaterSamplingGroundControlStation", "Simulation Mode"))
        self.Land.setText(_translate("WaterSamplingGroundControlStation", "Land"))
        self.Takeoff.setText(_translate("WaterSamplingGroundControlStation", "Takeoff"))
        self.ARM.setText(_translate("WaterSamplingGroundControlStation", "Arm"))
        self.OFFBOARD.setText(_translate("WaterSamplingGroundControlStation", "OFFBOARD"))
        self.POSCTL.setText(_translate("WaterSamplingGroundControlStation", "POSCTL"))
        self.StateSimulation.setText(_translate("WaterSamplingGroundControlStation", "Uninitialized"))
        self.GPSLabel_5.setText(_translate("WaterSamplingGroundControlStation", "GEOFENCE (Relative XYZ)"))
        self.GPSLabel_7.setText(_translate("WaterSamplingGroundControlStation", "Commanded Attitude (°) "))
        self.GPSLabel_9.setText(_translate("WaterSamplingGroundControlStation", "Thrust"))
        self.HOLD.setText(_translate("WaterSamplingGroundControlStation", "HOLD"))
        self.HOLD.setShortcut(_translate("WaterSamplingGroundControlStation", "Esc"))
        self.SetHome.setText(_translate("WaterSamplingGroundControlStation", "Set Home"))
        WaterSamplingGroundControlStation.setTabText(WaterSamplingGroundControlStation.indexOf(self.AutonomousFlightMode_Tab), _translate("WaterSamplingGroundControlStation", "Autonomous Flight"))
        self.titleWaterSampling.setText(_translate("WaterSamplingGroundControlStation", "Water Sampling"))
        self.lblRawEncoder.setText(_translate("WaterSamplingGroundControlStation", "RAW Encoder Readings"))
        self.lblRawX.setText(_translate("WaterSamplingGroundControlStation", "X"))
        self.lblRawY.setText(_translate("WaterSamplingGroundControlStation", "Y"))
        self.lblRawZ.setText(_translate("WaterSamplingGroundControlStation", "Z"))
        self.lblPosEst.setText(_translate("WaterSamplingGroundControlStation", "Payload Position Estimate (m)"))
        self.lblPayloadX.setText(_translate("WaterSamplingGroundControlStation", "X"))
        self.lblPayloadY.setText(_translate("WaterSamplingGroundControlStation", "Y"))
        self.lblPayloadZ.setText(_translate("WaterSamplingGroundControlStation", "Z (Length)"))
        self.titleControls.setText(_translate("WaterSamplingGroundControlStation", "Controls"))
        self.btnGetCurLenght.setText(_translate("WaterSamplingGroundControlStation", "Get Current"))
        self.btnSendCMD.setText(_translate("WaterSamplingGroundControlStation", "Send Command"))
        self.btnSendCMD.setShortcut(_translate("WaterSamplingGroundControlStation", "Return"))
        self.lblVelEst.setText(_translate("WaterSamplingGroundControlStation", "Payload Velocity Estimate (m/s)"))
        self.lblPayloadXDot.setText(_translate("WaterSamplingGroundControlStation", "X"))
        self.lblPayloadYDot.setText(_translate("WaterSamplingGroundControlStation", "Y"))
        self.lblPayloadZDot.setText(_translate("WaterSamplingGroundControlStation", "Z"))
        self.lblRawEncoderSpd.setText(_translate("WaterSamplingGroundControlStation", "RAW Encoder Speed (pps)"))
        self.lblXDot.setText(_translate("WaterSamplingGroundControlStation", "X"))
        self.lblYDot.setText(_translate("WaterSamplingGroundControlStation", "Y"))
        self.lblZDot.setText(_translate("WaterSamplingGroundControlStation", "Z"))
        self.btnDown.setText(_translate("WaterSamplingGroundControlStation", "Down"))
        self.btnUp.setText(_translate("WaterSamplingGroundControlStation", "Up"))
        self.btnUp.setShortcut(_translate("WaterSamplingGroundControlStation", "Return"))
        self.titleCableLog.setText(_translate("WaterSamplingGroundControlStation", "Cable Log"))
        self.FlightTimeLabel_2.setText(_translate("WaterSamplingGroundControlStation", "Flight Time"))
        self.Min_Label_2.setText(_translate("WaterSamplingGroundControlStation", "Min"))
        self.Sec_Label_2.setText(_translate("WaterSamplingGroundControlStation", "Secs"))
        self.lblDesiredCableLength.setText(_translate("WaterSamplingGroundControlStation", "Desired Cable Length"))
        self.lblAmplitude_2.setText(_translate("WaterSamplingGroundControlStation", "Length"))
        self.lblSpeed_2.setText(_translate("WaterSamplingGroundControlStation", "Speed"))
        self.lblStepperMotorControl.setText(_translate("WaterSamplingGroundControlStation", "Stepper Motor Control"))
        self.lblIncrement.setText(_translate("WaterSamplingGroundControlStation", "Movement Increment"))
        self.lblSpeed.setText(_translate("WaterSamplingGroundControlStation", "Frequency (Hz)"))
        self.lblTesting.setText(_translate("WaterSamplingGroundControlStation", "Testing (Sine Wave)"))
        self.lblAmplitude.setText(_translate("WaterSamplingGroundControlStation", "Amplitude"))
        self.btnStartTest.setText(_translate("WaterSamplingGroundControlStation", "Start"))
        self.btnStopTest.setText(_translate("WaterSamplingGroundControlStation", "Stop"))
        WaterSamplingGroundControlStation.setTabText(WaterSamplingGroundControlStation.indexOf(self.tab), _translate("WaterSamplingGroundControlStation", "Water Sampling"))
        self.ManualFlightTitle.setText(_translate("WaterSamplingGroundControlStation", "Manual Flight"))
        self.FlightTimeLabel_4.setText(_translate("WaterSamplingGroundControlStation", "Flight Time"))
        self.Min_Label_4.setText(_translate("WaterSamplingGroundControlStation", "Minutes"))
        self.Sec_Label_4.setText(_translate("WaterSamplingGroundControlStation", "Seconds"))
        self.GPSLabel_4.setText(_translate("WaterSamplingGroundControlStation", "GPS"))
        self.LatLabel_4.setText(_translate("WaterSamplingGroundControlStation", "Lateral"))
        self.LongLabel_4.setText(_translate("WaterSamplingGroundControlStation", "Longitudinal"))
        self.AltLabel_4.setText(_translate("WaterSamplingGroundControlStation", "Altitude"))
        self.BatLabel_4.setText(_translate("WaterSamplingGroundControlStation", "Battery Level"))
        self.FlightLogTitle_2.setText(_translate("WaterSamplingGroundControlStation", "Flight Log"))
        self.GetCurrentPositionUAV_2.setText(_translate("WaterSamplingGroundControlStation", "Get Current Position"))
        self.GetCurrentPositionPayload_2.setText(_translate("WaterSamplingGroundControlStation", "Get  Pos. Payload"))
        self.SendPositionPayload_2.setText(_translate("WaterSamplingGroundControlStation", "Send pos. Payload"))
        self.DesiredFlightCoordinates_2.setText(_translate("WaterSamplingGroundControlStation", "Desired Flight Coordinates"))
        self.XLabel1_2.setText(_translate("WaterSamplingGroundControlStation", "X"))
        self.YLabel1_2.setText(_translate("WaterSamplingGroundControlStation", "Y"))
        self.ZLabel1_2.setText(_translate("WaterSamplingGroundControlStation", "Z"))
        self.WLabel1_2.setText(_translate("WaterSamplingGroundControlStation", "W"))
        self.SendPositionUAV_2.setText(_translate("WaterSamplingGroundControlStation", "Send New Position"))
        self.FlightDistLabel_4.setText(_translate("WaterSamplingGroundControlStation", "Flight Distance"))
        self.Meters_Label_4.setText(_translate("WaterSamplingGroundControlStation", "Meters"))
        self.VelLabel_4.setText(_translate("WaterSamplingGroundControlStation", "Velocity"))
        self.U_VEL_Label_4.setText(_translate("WaterSamplingGroundControlStation", "U"))
        self.V_VEL_Label_4.setText(_translate("WaterSamplingGroundControlStation", "V"))
        self.W_VEL_Label_4.setText(_translate("WaterSamplingGroundControlStation", "W"))
        self.EmergencyStop_2.setText(_translate("WaterSamplingGroundControlStation", "Emergency Stop"))
        self.IMULabel_4.setText(_translate("WaterSamplingGroundControlStation", "IMU"))
        self.XLabel0_2.setText(_translate("WaterSamplingGroundControlStation", "X"))
        self.YLabel0_2.setText(_translate("WaterSamplingGroundControlStation", "Y"))
        self.ZLabel0_2.setText(_translate("WaterSamplingGroundControlStation", "Z"))
        self.WLabel0_2.setText(_translate("WaterSamplingGroundControlStation", "W"))
        self.DesiredWaterSamplingPayloadCoordinates_2.setText(_translate("WaterSamplingGroundControlStation", "<html><head/><body><p align=\"center\">Desired Water Sampling </p><p align=\"center\">Payload Coordinates</p></body></html>"))
        self.XLabel2_2.setText(_translate("WaterSamplingGroundControlStation", "X"))
        self.YLabel2_2.setText(_translate("WaterSamplingGroundControlStation", "Y"))
        self.ZLabel2_2.setText(_translate("WaterSamplingGroundControlStation", "Z"))
        self.WLabel2_2.setText(_translate("WaterSamplingGroundControlStation", "W"))
        WaterSamplingGroundControlStation.setTabText(WaterSamplingGroundControlStation.indexOf(self.ManualFlightManagment_Tab), _translate("WaterSamplingGroundControlStation", "Manual Flight"))
        self.ReferencesTitle.setText(_translate("WaterSamplingGroundControlStation", "References"))
        self.ReferencesInfo.setText(_translate("WaterSamplingGroundControlStation", "<html><head/><body><p>[1] https://wiki.ros.org/roscore</p><p>[2] https://wiki.ros.org/mavros</p><p>[3] https://docs.px4.io/main/en/flight_controller/pixhawk.html</p><p>[4] https://docs.px4.io/main/en/flight_modes/offboard.html</p></body></html>"))
        WaterSamplingGroundControlStation.setTabText(WaterSamplingGroundControlStation.indexOf(self.References_Tab), _translate("WaterSamplingGroundControlStation", "References"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WaterSamplingGroundControlStation = QtWidgets.QTabWidget()
    ui = Ui_WaterSamplingGroundControlStation()
    ui.setupUi(WaterSamplingGroundControlStation)
    WaterSamplingGroundControlStation.show()
    sys.exit(app.exec_())
