# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_Sampler.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WaterSamplingGroundControlStation(object):
    def setupUi(self, WaterSamplingGroundControlStation):
        WaterSamplingGroundControlStation.setObjectName("WaterSamplingGroundControlStation")
        WaterSamplingGroundControlStation.resize(1331, 857)
        self.Initialization_Tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Initialization_Tab.setFont(font)
        self.Initialization_Tab.setObjectName("Initialization_Tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Initialization_Tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 941, 761))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.InitVLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.InitVLayout.setContentsMargins(0, 0, 0, 0)
        self.InitVLayout.setObjectName("InitVLayout")
        self.InitTitle = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.InitTitle.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.InitTitle.setFont(font)
        self.InitTitle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.InitTitle.setObjectName("InitTitle")
        self.InitVLayout.addWidget(self.InitTitle)
        self.Welcome = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Welcome.setWordWrap(True)
        self.Welcome.setObjectName("Welcome")
        self.InitVLayout.addWidget(self.Welcome)
        self.ROSCoreInfo = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.ROSCoreInfo.setWordWrap(True)
        self.ROSCoreInfo.setObjectName("ROSCoreInfo")
        self.InitVLayout.addWidget(self.ROSCoreInfo)
        self.StartROSCore = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.StartROSCore.setObjectName("StartROSCore")
        self.InitVLayout.addWidget(self.StartROSCore)
        self.MAVROSInfo = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.MAVROSInfo.setFrameShadow(QtWidgets.QFrame.Plain)
        self.MAVROSInfo.setWordWrap(True)
        self.MAVROSInfo.setObjectName("MAVROSInfo")
        self.InitVLayout.addWidget(self.MAVROSInfo)
        self.StartMAVROS = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.StartMAVROS.setObjectName("StartMAVROS")
        self.InitVLayout.addWidget(self.StartMAVROS)
        self.OFFBOARDInfo = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.OFFBOARDInfo.setWordWrap(True)
        self.OFFBOARDInfo.setObjectName("OFFBOARDInfo")
        self.InitVLayout.addWidget(self.OFFBOARDInfo)
        self.StartOffboard = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.StartOffboard.setObjectName("StartOffboard")
        self.InitVLayout.addWidget(self.StartOffboard)
        WaterSamplingGroundControlStation.addTab(self.Initialization_Tab, "")
        self.AutonomousFlightMode_Tab = QtWidgets.QWidget()
        self.AutonomousFlightMode_Tab.setObjectName("AutonomousFlightMode_Tab")
        self.AutonomousTitle = QtWidgets.QLabel(self.AutonomousFlightMode_Tab)
        self.AutonomousTitle.setGeometry(QtCore.QRect(20, 10, 481, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.AutonomousTitle.setFont(font)
        self.AutonomousTitle.setObjectName("AutonomousTitle")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 80, 301, 181))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.GPSDataLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.GPSDataLayout.setContentsMargins(0, 0, 0, 0)
        self.GPSDataLayout.setObjectName("GPSDataLayout")
        self.GPSLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.GPSLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.GPSLabel.setObjectName("GPSLabel")
        self.GPSDataLayout.addWidget(self.GPSLabel)
        self.GPSHLayout = QtWidgets.QHBoxLayout()
        self.GPSHLayout.setObjectName("GPSHLayout")
        self.LatLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.LatLabel.setObjectName("LatLabel")
        self.GPSHLayout.addWidget(self.LatLabel)
        self.LongLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.LongLabel.setObjectName("LongLabel")
        self.GPSHLayout.addWidget(self.LongLabel)
        self.AltLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.AltLabel.setObjectName("AltLabel")
        self.GPSHLayout.addWidget(self.AltLabel)
        self.GPSDataLayout.addLayout(self.GPSHLayout)
        self.GPS_DISP = QtWidgets.QHBoxLayout()
        self.GPS_DISP.setObjectName("GPS_DISP")
        self.LatGPS_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_2)
        self.LatGPS_DISP.setObjectName("LatGPS_DISP")
        self.GPS_DISP.addWidget(self.LatGPS_DISP)
        self.LongGPS_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_2)
        self.LongGPS_DISP.setObjectName("LongGPS_DISP")
        self.GPS_DISP.addWidget(self.LongGPS_DISP)
        self.AltGPS_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_2)
        self.AltGPS_DISP.setObjectName("AltGPS_DISP")
        self.GPS_DISP.addWidget(self.AltGPS_DISP)
        self.GPSDataLayout.addLayout(self.GPS_DISP)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(340, 270, 301, 191))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.IMULayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.IMULayout.setContentsMargins(0, 0, 0, 0)
        self.IMULayout.setObjectName("IMULayout")
        self.IMULabel = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.IMULabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.IMULabel.setObjectName("IMULabel")
        self.IMULayout.addWidget(self.IMULabel)
        self.IMUHLayout = QtWidgets.QHBoxLayout()
        self.IMUHLayout.setObjectName("IMUHLayout")
        self.XLabel0 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.XLabel0.setObjectName("XLabel0")
        self.IMUHLayout.addWidget(self.XLabel0)
        self.YLabel0 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.YLabel0.setObjectName("YLabel0")
        self.IMUHLayout.addWidget(self.YLabel0)
        self.ZLabel0 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.ZLabel0.setObjectName("ZLabel0")
        self.IMUHLayout.addWidget(self.ZLabel0)
        self.IMULayout.addLayout(self.IMUHLayout)
        self.IMU_DISP = QtWidgets.QHBoxLayout()
        self.IMU_DISP.setObjectName("IMU_DISP")
        self.X_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_4)
        self.X_DISP.setObjectName("X_DISP")
        self.IMU_DISP.addWidget(self.X_DISP)
        self.Y_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_4)
        self.Y_DISP.setObjectName("Y_DISP")
        self.IMU_DISP.addWidget(self.Y_DISP)
        self.Z_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_4)
        self.Z_DISP.setDigitCount(6)
        self.Z_DISP.setObjectName("Z_DISP")
        self.IMU_DISP.addWidget(self.Z_DISP)
        self.IMULayout.addLayout(self.IMU_DISP)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(20, 270, 301, 191))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.VelVLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.VelVLayout.setContentsMargins(0, 0, 0, 0)
        self.VelVLayout.setObjectName("VelVLayout")
        self.VelLabel = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.VelLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.VelLabel.setObjectName("VelLabel")
        self.VelVLayout.addWidget(self.VelLabel)
        self.VelHLabel = QtWidgets.QHBoxLayout()
        self.VelHLabel.setObjectName("VelHLabel")
        self.U_VEL_Label = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.U_VEL_Label.setObjectName("U_VEL_Label")
        self.VelHLabel.addWidget(self.U_VEL_Label)
        self.V_VEL_Label = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.V_VEL_Label.setObjectName("V_VEL_Label")
        self.VelHLabel.addWidget(self.V_VEL_Label)
        self.W_VEL_Label = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.W_VEL_Label.setObjectName("W_VEL_Label")
        self.VelHLabel.addWidget(self.W_VEL_Label)
        self.VelVLayout.addLayout(self.VelHLabel)
        self.Vel_DISP = QtWidgets.QHBoxLayout()
        self.Vel_DISP.setObjectName("Vel_DISP")
        self.U_Vel_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_5)
        self.U_Vel_DISP.setObjectName("U_Vel_DISP")
        self.Vel_DISP.addWidget(self.U_Vel_DISP)
        self.V_Vel_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_5)
        self.V_Vel_DISP.setObjectName("V_Vel_DISP")
        self.Vel_DISP.addWidget(self.V_Vel_DISP)
        self.W_Vel_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_5)
        self.W_Vel_DISP.setObjectName("W_Vel_DISP")
        self.Vel_DISP.addWidget(self.W_Vel_DISP)
        self.VelVLayout.addLayout(self.Vel_DISP)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(660, 170, 160, 110))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.FlightTimeVLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.FlightTimeVLayout.setContentsMargins(0, 0, 0, 0)
        self.FlightTimeVLayout.setObjectName("FlightTimeVLayout")
        self.FlightTimeLabel = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.FlightTimeLabel.setObjectName("FlightTimeLabel")
        self.FlightTimeVLayout.addWidget(self.FlightTimeLabel)
        self.FlightTimeHLabel = QtWidgets.QHBoxLayout()
        self.FlightTimeHLabel.setObjectName("FlightTimeHLabel")
        self.Min_Label = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.Min_Label.setObjectName("Min_Label")
        self.FlightTimeHLabel.addWidget(self.Min_Label)
        self.Sec_Label = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.Sec_Label.setObjectName("Sec_Label")
        self.FlightTimeHLabel.addWidget(self.Sec_Label)
        self.FlightTimeVLayout.addLayout(self.FlightTimeHLabel)
        self.FlightTime_DISP = QtWidgets.QHBoxLayout()
        self.FlightTime_DISP.setObjectName("FlightTime_DISP")
        self.Min_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_6)
        self.Min_DISP.setObjectName("Min_DISP")
        self.FlightTime_DISP.addWidget(self.Min_DISP)
        self.Sec_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_6)
        self.Sec_DISP.setObjectName("Sec_DISP")
        self.FlightTime_DISP.addWidget(self.Sec_DISP)
        self.FlightTimeVLayout.addLayout(self.FlightTime_DISP)
        self.Logging = QtWidgets.QTextBrowser(self.AutonomousFlightMode_Tab)
        self.Logging.setGeometry(QtCore.QRect(1020, 80, 301, 721))
        self.Logging.setObjectName("Logging")
        self.FlightLogTitle = QtWidgets.QLabel(self.AutonomousFlightMode_Tab)
        self.FlightLogTitle.setGeometry(QtCore.QRect(1060, 20, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.FlightLogTitle.setFont(font)
        self.FlightLogTitle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.FlightLogTitle.setObjectName("FlightLogTitle")
        self.verticalLayoutWidget_15 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.verticalLayoutWidget_15.setGeometry(QtCore.QRect(20, 570, 301, 191))
        self.verticalLayoutWidget_15.setObjectName("verticalLayoutWidget_15")
        self.DesiredFlightLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_15)
        self.DesiredFlightLayout.setContentsMargins(0, 0, 0, 0)
        self.DesiredFlightLayout.setObjectName("DesiredFlightLayout")
        self.DesiredFlightCoordinates = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.DesiredFlightCoordinates.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.DesiredFlightCoordinates.setObjectName("DesiredFlightCoordinates")
        self.DesiredFlightLayout.addWidget(self.DesiredFlightCoordinates)
        self.FlightHLayout = QtWidgets.QHBoxLayout()
        self.FlightHLayout.setObjectName("FlightHLayout")
        self.XLabel1 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.XLabel1.setObjectName("XLabel1")
        self.FlightHLayout.addWidget(self.XLabel1)
        self.YLabel1 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.YLabel1.setObjectName("YLabel1")
        self.FlightHLayout.addWidget(self.YLabel1)
        self.ZLabel1 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.ZLabel1.setObjectName("ZLabel1")
        self.FlightHLayout.addWidget(self.ZLabel1)
        self.DesiredFlightLayout.addLayout(self.FlightHLayout)
        self.FlightHLayout1 = QtWidgets.QHBoxLayout()
        self.FlightHLayout1.setObjectName("FlightHLayout1")
        self.XPositionUAV = QtWidgets.QLineEdit(self.verticalLayoutWidget_15)
        self.XPositionUAV.setObjectName("XPositionUAV")
        self.FlightHLayout1.addWidget(self.XPositionUAV)
        self.YPositionUAV = QtWidgets.QLineEdit(self.verticalLayoutWidget_15)
        self.YPositionUAV.setObjectName("YPositionUAV")
        self.FlightHLayout1.addWidget(self.YPositionUAV)
        self.ZPositionUAV = QtWidgets.QLineEdit(self.verticalLayoutWidget_15)
        self.ZPositionUAV.setObjectName("ZPositionUAV")
        self.FlightHLayout1.addWidget(self.ZPositionUAV)
        self.DesiredFlightLayout.addLayout(self.FlightHLayout1)
        self.GetCurrentPositionUAV = QtWidgets.QPushButton(self.AutonomousFlightMode_Tab)
        self.GetCurrentPositionUAV.setGeometry(QtCore.QRect(20, 770, 141, 31))
        self.GetCurrentPositionUAV.setObjectName("GetCurrentPositionUAV")
        self.EmergencyStop = QtWidgets.QPushButton(self.AutonomousFlightMode_Tab)
        self.EmergencyStop.setGeometry(QtCore.QRect(670, 720, 321, 81))
        self.EmergencyStop.setObjectName("EmergencyStop")
        self.SendPositionUAV = QtWidgets.QPushButton(self.AutonomousFlightMode_Tab)
        self.SendPositionUAV.setGeometry(QtCore.QRect(180, 770, 141, 31))
        self.SendPositionUAV.setObjectName("SendPositionUAV")
        self.GetCurrentPositionPayload = QtWidgets.QPushButton(self.AutonomousFlightMode_Tab)
        self.GetCurrentPositionPayload.setGeometry(QtCore.QRect(340, 770, 141, 31))
        self.GetCurrentPositionPayload.setObjectName("GetCurrentPositionPayload")
        self.verticalLayoutWidget_16 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.verticalLayoutWidget_16.setGeometry(QtCore.QRect(340, 570, 301, 191))
        self.verticalLayoutWidget_16.setObjectName("verticalLayoutWidget_16")
        self.WaterSamplingLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_16)
        self.WaterSamplingLayout.setContentsMargins(0, 0, 0, 0)
        self.WaterSamplingLayout.setObjectName("WaterSamplingLayout")
        self.DesiredWaterSamplingPayloadCoordinates = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.DesiredWaterSamplingPayloadCoordinates.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.DesiredWaterSamplingPayloadCoordinates.setObjectName("DesiredWaterSamplingPayloadCoordinates")
        self.WaterSamplingLayout.addWidget(self.DesiredWaterSamplingPayloadCoordinates)
        self.WaterHLayout = QtWidgets.QHBoxLayout()
        self.WaterHLayout.setObjectName("WaterHLayout")
        self.XLabel2 = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.XLabel2.setObjectName("XLabel2")
        self.WaterHLayout.addWidget(self.XLabel2)
        self.YLabel2 = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.YLabel2.setObjectName("YLabel2")
        self.WaterHLayout.addWidget(self.YLabel2)
        self.ZLabel2 = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.ZLabel2.setObjectName("ZLabel2")
        self.WaterHLayout.addWidget(self.ZLabel2)
        self.WaterSamplingLayout.addLayout(self.WaterHLayout)
        self.WaterHLayout1 = QtWidgets.QHBoxLayout()
        self.WaterHLayout1.setObjectName("WaterHLayout1")
        self.XPositionPayload = QtWidgets.QLineEdit(self.verticalLayoutWidget_16)
        self.XPositionPayload.setObjectName("XPositionPayload")
        self.WaterHLayout1.addWidget(self.XPositionPayload)
        self.YPositionPayload = QtWidgets.QLineEdit(self.verticalLayoutWidget_16)
        self.YPositionPayload.setObjectName("YPositionPayload")
        self.WaterHLayout1.addWidget(self.YPositionPayload)
        self.ZPositionPayload = QtWidgets.QLineEdit(self.verticalLayoutWidget_16)
        self.ZPositionPayload.setObjectName("ZPositionPayload")
        self.WaterHLayout1.addWidget(self.ZPositionPayload)
        self.WaterSamplingLayout.addLayout(self.WaterHLayout1)
        self.SendPositionPayload = QtWidgets.QPushButton(self.AutonomousFlightMode_Tab)
        self.SendPositionPayload.setGeometry(QtCore.QRect(500, 770, 141, 31))
        self.SendPositionPayload.setObjectName("SendPositionPayload")
        self.verticalLayoutWidget_14 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.verticalLayoutWidget_14.setGeometry(QtCore.QRect(340, 80, 301, 181))
        self.verticalLayoutWidget_14.setObjectName("verticalLayoutWidget_14")
        self.GPSDataLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_14)
        self.GPSDataLayout_3.setContentsMargins(0, 0, 0, 0)
        self.GPSDataLayout_3.setObjectName("GPSDataLayout_3")
        self.GPSLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.GPSLabel_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.GPSLabel_2.setObjectName("GPSLabel_2")
        self.GPSDataLayout_3.addWidget(self.GPSLabel_2)
        self.GPSHLayout_2 = QtWidgets.QHBoxLayout()
        self.GPSHLayout_2.setObjectName("GPSHLayout_2")
        self.LatLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.LatLabel_2.setObjectName("LatLabel_2")
        self.GPSHLayout_2.addWidget(self.LatLabel_2)
        self.LongLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.LongLabel_2.setObjectName("LongLabel_2")
        self.GPSHLayout_2.addWidget(self.LongLabel_2)
        self.AltLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget_14)
        self.AltLabel_2.setObjectName("AltLabel_2")
        self.GPSHLayout_2.addWidget(self.AltLabel_2)
        self.GPSDataLayout_3.addLayout(self.GPSHLayout_2)
        self.GPS_DISP_2 = QtWidgets.QHBoxLayout()
        self.GPS_DISP_2.setObjectName("GPS_DISP_2")
        self.RelX_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_14)
        self.RelX_DISP.setObjectName("RelX_DISP")
        self.GPS_DISP_2.addWidget(self.RelX_DISP)
        self.RelY_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_14)
        self.RelY_DISP.setObjectName("RelY_DISP")
        self.GPS_DISP_2.addWidget(self.RelY_DISP)
        self.AGL_DISP = QtWidgets.QLCDNumber(self.verticalLayoutWidget_14)
        self.AGL_DISP.setObjectName("AGL_DISP")
        self.GPS_DISP_2.addWidget(self.AGL_DISP)
        self.GPSDataLayout_3.addLayout(self.GPS_DISP_2)
        self.AutonomousTitle_2 = QtWidgets.QLabel(self.AutonomousFlightMode_Tab)
        self.AutonomousTitle_2.setGeometry(QtCore.QRect(20, 500, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.AutonomousTitle_2.setFont(font)
        self.AutonomousTitle_2.setObjectName("AutonomousTitle_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(660, 80, 161, 71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.BatLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.BatLayout.setContentsMargins(0, 0, 0, 0)
        self.BatLayout.setObjectName("BatLayout")
        self.Voltage_Label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Voltage_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Voltage_Label.setObjectName("Voltage_Label")
        self.BatLayout.addWidget(self.Voltage_Label, 0, 0, 1, 1)
        self.VOLT_DISP = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.VOLT_DISP.setObjectName("VOLT_DISP")
        self.BatLayout.addWidget(self.VOLT_DISP, 0, 1, 1, 1)
        self.BatInd = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.BatInd.setProperty("value", 20)
        self.BatInd.setTextVisible(False)
        self.BatInd.setObjectName("BatInd")
        self.BatLayout.addWidget(self.BatInd, 1, 0, 1, 2)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(840, 80, 160, 80))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.StateConnected = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.StateConnected.setStyleSheet("color : red")
        self.StateConnected.setFrameShape(QtWidgets.QFrame.Box)
        self.StateConnected.setFrameShadow(QtWidgets.QFrame.Plain)
        self.StateConnected.setAlignment(QtCore.Qt.AlignCenter)
        self.StateConnected.setObjectName("StateConnected")
        self.verticalLayout.addWidget(self.StateConnected)
        self.StateARM = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.StateARM.setStyleSheet("color : green")
        self.StateARM.setFrameShape(QtWidgets.QFrame.Box)
        self.StateARM.setFrameShadow(QtWidgets.QFrame.Plain)
        self.StateARM.setAlignment(QtCore.Qt.AlignCenter)
        self.StateARM.setObjectName("StateARM")
        self.verticalLayout.addWidget(self.StateARM)
        self.StateMode = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.StateMode.setStyleSheet("")
        self.StateMode.setFrameShape(QtWidgets.QFrame.Box)
        self.StateMode.setFrameShadow(QtWidgets.QFrame.Plain)
        self.StateMode.setAlignment(QtCore.Qt.AlignCenter)
        self.StateMode.setObjectName("StateMode")
        self.verticalLayout.addWidget(self.StateMode)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.AutonomousFlightMode_Tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(670, 570, 321, 141))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Takeoff = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.Takeoff.setObjectName("Takeoff")
        self.gridLayout.addWidget(self.Takeoff, 3, 0, 1, 1)
        self.DISARM = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.DISARM.setObjectName("DISARM")
        self.gridLayout.addWidget(self.DISARM, 2, 1, 1, 1)
        self.SimulationMode = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.SimulationMode.setChecked(True)
        self.SimulationMode.setObjectName("SimulationMode")
        self.gridLayout.addWidget(self.SimulationMode, 0, 0, 1, 1)
        self.ARM = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ARM.setObjectName("ARM")
        self.gridLayout.addWidget(self.ARM, 2, 0, 1, 1)
        self.TakeoffHeight = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TakeoffHeight.sizePolicy().hasHeightForWidth())
        self.TakeoffHeight.setSizePolicy(sizePolicy)
        self.TakeoffHeight.setObjectName("TakeoffHeight")
        self.gridLayout.addWidget(self.TakeoffHeight, 3, 1, 1, 1)
        self.SetHome = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.SetHome.setObjectName("SetHome")
        self.gridLayout.addWidget(self.SetHome, 0, 1, 1, 1)
        self.Land = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Land.sizePolicy().hasHeightForWidth())
        self.Land.setSizePolicy(sizePolicy)
        self.Land.setObjectName("Land")
        self.gridLayout.addWidget(self.Land, 4, 0, 1, 2)
        WaterSamplingGroundControlStation.addTab(self.AutonomousFlightMode_Tab, "")
        self.ManualFlightManagment_Tab = QtWidgets.QWidget()
        self.ManualFlightManagment_Tab.setObjectName("ManualFlightManagment_Tab")
        self.ManualFlightTitle = QtWidgets.QLabel(self.ManualFlightManagment_Tab)
        self.ManualFlightTitle.setGeometry(QtCore.QRect(10, 0, 321, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.ManualFlightTitle.setFont(font)
        self.ManualFlightTitle.setObjectName("ManualFlightTitle")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.ManualFlightManagment_Tab)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(770, 10, 160, 110))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.FlightTimeVLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.FlightTimeVLayout_4.setContentsMargins(0, 0, 0, 0)
        self.FlightTimeVLayout_4.setObjectName("FlightTimeVLayout_4")
        self.FlightTimeLabel_4 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.FlightTimeLabel_4.setObjectName("FlightTimeLabel_4")
        self.FlightTimeVLayout_4.addWidget(self.FlightTimeLabel_4)
        self.FlightTimeHLabel_4 = QtWidgets.QHBoxLayout()
        self.FlightTimeHLabel_4.setObjectName("FlightTimeHLabel_4")
        self.Min_Label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.Min_Label_4.setObjectName("Min_Label_4")
        self.FlightTimeHLabel_4.addWidget(self.Min_Label_4)
        self.Sec_Label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.Sec_Label_4.setObjectName("Sec_Label_4")
        self.FlightTimeHLabel_4.addWidget(self.Sec_Label_4)
        self.FlightTimeVLayout_4.addLayout(self.FlightTimeHLabel_4)
        self.FlightTime_DISP_4 = QtWidgets.QHBoxLayout()
        self.FlightTime_DISP_4.setObjectName("FlightTime_DISP_4")
        self.Min_DISP_4 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_8)
        self.Min_DISP_4.setObjectName("Min_DISP_4")
        self.FlightTime_DISP_4.addWidget(self.Min_DISP_4)
        self.Sec_DISP_4 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_8)
        self.Sec_DISP_4.setObjectName("Sec_DISP_4")
        self.FlightTime_DISP_4.addWidget(self.Sec_DISP_4)
        self.FlightTimeVLayout_4.addLayout(self.FlightTime_DISP_4)
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.ManualFlightManagment_Tab)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(10, 100, 301, 181))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.GPSDataLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.GPSDataLayout_2.setContentsMargins(0, 0, 0, 0)
        self.GPSDataLayout_2.setObjectName("GPSDataLayout_2")
        self.GPSLabel_4 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.GPSLabel_4.setObjectName("GPSLabel_4")
        self.GPSDataLayout_2.addWidget(self.GPSLabel_4)
        self.GPSHLayout_4 = QtWidgets.QHBoxLayout()
        self.GPSHLayout_4.setObjectName("GPSHLayout_4")
        self.LatLabel_4 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.LatLabel_4.setObjectName("LatLabel_4")
        self.GPSHLayout_4.addWidget(self.LatLabel_4)
        self.LongLabel_4 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.LongLabel_4.setObjectName("LongLabel_4")
        self.GPSHLayout_4.addWidget(self.LongLabel_4)
        self.AltLabel_4 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.AltLabel_4.setObjectName("AltLabel_4")
        self.GPSHLayout_4.addWidget(self.AltLabel_4)
        self.GPSDataLayout_2.addLayout(self.GPSHLayout_4)
        self.GPS_DISP_4 = QtWidgets.QHBoxLayout()
        self.GPS_DISP_4.setObjectName("GPS_DISP_4")
        self.LatGPS_DISP_4 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_9)
        self.LatGPS_DISP_4.setObjectName("LatGPS_DISP_4")
        self.GPS_DISP_4.addWidget(self.LatGPS_DISP_4)
        self.LongGPS_DISP_4 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_9)
        self.LongGPS_DISP_4.setObjectName("LongGPS_DISP_4")
        self.GPS_DISP_4.addWidget(self.LongGPS_DISP_4)
        self.AltGPS_DISP_4 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_9)
        self.AltGPS_DISP_4.setObjectName("AltGPS_DISP_4")
        self.GPS_DISP_4.addWidget(self.AltGPS_DISP_4)
        self.GPSDataLayout_2.addLayout(self.GPS_DISP_4)
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.ManualFlightManagment_Tab)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(410, 10, 160, 80))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.BatLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.BatLayout_2.setContentsMargins(0, 0, 0, 0)
        self.BatLayout_2.setObjectName("BatLayout_2")
        self.BatLabel_4 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        self.BatLabel_4.setObjectName("BatLabel_4")
        self.BatLayout_2.addWidget(self.BatLabel_4)
        self.BatInd_4 = QtWidgets.QProgressBar(self.verticalLayoutWidget_10)
        self.BatInd_4.setProperty("value", 24)
        self.BatInd_4.setObjectName("BatInd_4")
        self.BatLayout_2.addWidget(self.BatInd_4)
        self.FlightLogTitle_2 = QtWidgets.QLabel(self.ManualFlightManagment_Tab)
        self.FlightLogTitle_2.setGeometry(QtCore.QRect(740, 250, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.FlightLogTitle_2.setFont(font)
        self.FlightLogTitle_2.setObjectName("FlightLogTitle_2")
        self.Logging_2 = QtWidgets.QTextBrowser(self.ManualFlightManagment_Tab)
        self.Logging_2.setGeometry(QtCore.QRect(620, 300, 321, 481))
        self.Logging_2.setObjectName("Logging_2")
        self.GetCurrentPositionUAV_2 = QtWidgets.QPushButton(self.ManualFlightManagment_Tab)
        self.GetCurrentPositionUAV_2.setGeometry(QtCore.QRect(10, 490, 141, 31))
        self.GetCurrentPositionUAV_2.setObjectName("GetCurrentPositionUAV_2")
        self.GetCurrentPositionPayload_2 = QtWidgets.QPushButton(self.ManualFlightManagment_Tab)
        self.GetCurrentPositionPayload_2.setGeometry(QtCore.QRect(10, 730, 141, 31))
        self.GetCurrentPositionPayload_2.setObjectName("GetCurrentPositionPayload_2")
        self.SendPositionPayload_2 = QtWidgets.QPushButton(self.ManualFlightManagment_Tab)
        self.SendPositionPayload_2.setGeometry(QtCore.QRect(170, 730, 141, 31))
        self.SendPositionPayload_2.setObjectName("SendPositionPayload_2")
        self.verticalLayoutWidget_17 = QtWidgets.QWidget(self.ManualFlightManagment_Tab)
        self.verticalLayoutWidget_17.setGeometry(QtCore.QRect(10, 300, 301, 181))
        self.verticalLayoutWidget_17.setObjectName("verticalLayoutWidget_17")
        self.DesiredFlightLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_17)
        self.DesiredFlightLayout_2.setContentsMargins(0, 0, 0, 0)
        self.DesiredFlightLayout_2.setObjectName("DesiredFlightLayout_2")
        self.DesiredFlightCoordinates_2 = QtWidgets.QLabel(self.verticalLayoutWidget_17)
        self.DesiredFlightCoordinates_2.setObjectName("DesiredFlightCoordinates_2")
        self.DesiredFlightLayout_2.addWidget(self.DesiredFlightCoordinates_2)
        self.FlightHLayout_2 = QtWidgets.QHBoxLayout()
        self.FlightHLayout_2.setObjectName("FlightHLayout_2")
        self.XLabel1_2 = QtWidgets.QLabel(self.verticalLayoutWidget_17)
        self.XLabel1_2.setObjectName("XLabel1_2")
        self.FlightHLayout_2.addWidget(self.XLabel1_2)
        self.YLabel1_2 = QtWidgets.QLabel(self.verticalLayoutWidget_17)
        self.YLabel1_2.setObjectName("YLabel1_2")
        self.FlightHLayout_2.addWidget(self.YLabel1_2)
        self.ZLabel1_2 = QtWidgets.QLabel(self.verticalLayoutWidget_17)
        self.ZLabel1_2.setObjectName("ZLabel1_2")
        self.FlightHLayout_2.addWidget(self.ZLabel1_2)
        self.WLabel1_2 = QtWidgets.QLabel(self.verticalLayoutWidget_17)
        self.WLabel1_2.setObjectName("WLabel1_2")
        self.FlightHLayout_2.addWidget(self.WLabel1_2)
        self.DesiredFlightLayout_2.addLayout(self.FlightHLayout_2)
        self.FlightHLayout1_2 = QtWidgets.QHBoxLayout()
        self.FlightHLayout1_2.setObjectName("FlightHLayout1_2")
        self.XPositionUAV_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_17)
        self.XPositionUAV_2.setObjectName("XPositionUAV_2")
        self.FlightHLayout1_2.addWidget(self.XPositionUAV_2)
        self.YPositionUAV_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_17)
        self.YPositionUAV_2.setObjectName("YPositionUAV_2")
        self.FlightHLayout1_2.addWidget(self.YPositionUAV_2)
        self.ZPositionUAV_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_17)
        self.ZPositionUAV_2.setObjectName("ZPositionUAV_2")
        self.FlightHLayout1_2.addWidget(self.ZPositionUAV_2)
        self.WPositionUAV_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_17)
        self.WPositionUAV_2.setObjectName("WPositionUAV_2")
        self.FlightHLayout1_2.addWidget(self.WPositionUAV_2)
        self.DesiredFlightLayout_2.addLayout(self.FlightHLayout1_2)
        self.SendPositionUAV_2 = QtWidgets.QPushButton(self.ManualFlightManagment_Tab)
        self.SendPositionUAV_2.setGeometry(QtCore.QRect(170, 490, 141, 31))
        self.SendPositionUAV_2.setObjectName("SendPositionUAV_2")
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.ManualFlightManagment_Tab)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(590, 10, 160, 80))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.FlightDistVLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.FlightDistVLayout_4.setContentsMargins(0, 0, 0, 0)
        self.FlightDistVLayout_4.setObjectName("FlightDistVLayout_4")
        self.FlightDistLabel_4 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        self.FlightDistLabel_4.setObjectName("FlightDistLabel_4")
        self.FlightDistVLayout_4.addWidget(self.FlightDistLabel_4)
        self.FlightDistHLayout_4 = QtWidgets.QHBoxLayout()
        self.FlightDistHLayout_4.setObjectName("FlightDistHLayout_4")
        self.Meters_DISP_4 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_11)
        self.Meters_DISP_4.setObjectName("Meters_DISP_4")
        self.FlightDistHLayout_4.addWidget(self.Meters_DISP_4)
        self.Meters_Label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        self.Meters_Label_4.setObjectName("Meters_Label_4")
        self.FlightDistHLayout_4.addWidget(self.Meters_Label_4)
        self.FlightDistVLayout_4.addLayout(self.FlightDistHLayout_4)
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self.ManualFlightManagment_Tab)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(330, 300, 281, 181))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.VelVLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.VelVLayout_4.setContentsMargins(0, 0, 0, 0)
        self.VelVLayout_4.setObjectName("VelVLayout_4")
        self.VelLabel_4 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        self.VelLabel_4.setObjectName("VelLabel_4")
        self.VelVLayout_4.addWidget(self.VelLabel_4)
        self.VelHLabel_4 = QtWidgets.QHBoxLayout()
        self.VelHLabel_4.setObjectName("VelHLabel_4")
        self.U_VEL_Label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        self.U_VEL_Label_4.setObjectName("U_VEL_Label_4")
        self.VelHLabel_4.addWidget(self.U_VEL_Label_4)
        self.V_VEL_Label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        self.V_VEL_Label_4.setObjectName("V_VEL_Label_4")
        self.VelHLabel_4.addWidget(self.V_VEL_Label_4)
        self.W_VEL_Label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        self.W_VEL_Label_4.setObjectName("W_VEL_Label_4")
        self.VelHLabel_4.addWidget(self.W_VEL_Label_4)
        self.VelVLayout_4.addLayout(self.VelHLabel_4)
        self.Vel_DISP_4 = QtWidgets.QHBoxLayout()
        self.Vel_DISP_4.setObjectName("Vel_DISP_4")
        self.U_Vel_DISP_4 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_12)
        self.U_Vel_DISP_4.setObjectName("U_Vel_DISP_4")
        self.Vel_DISP_4.addWidget(self.U_Vel_DISP_4)
        self.V_Vel_DISP_4 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_12)
        self.V_Vel_DISP_4.setObjectName("V_Vel_DISP_4")
        self.Vel_DISP_4.addWidget(self.V_Vel_DISP_4)
        self.W_Vel_DISP_4 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_12)
        self.W_Vel_DISP_4.setObjectName("W_Vel_DISP_4")
        self.Vel_DISP_4.addWidget(self.W_Vel_DISP_4)
        self.VelVLayout_4.addLayout(self.Vel_DISP_4)
        self.EmergencyStop_2 = QtWidgets.QPushButton(self.ManualFlightManagment_Tab)
        self.EmergencyStop_2.setGeometry(QtCore.QRect(620, 130, 311, 121))
        self.EmergencyStop_2.setObjectName("EmergencyStop_2")
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(self.ManualFlightManagment_Tab)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(330, 100, 281, 181))
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.IMULayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.IMULayout_2.setContentsMargins(0, 0, 0, 0)
        self.IMULayout_2.setObjectName("IMULayout_2")
        self.IMULabel_4 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.IMULabel_4.setObjectName("IMULabel_4")
        self.IMULayout_2.addWidget(self.IMULabel_4)
        self.IMUHLayout_2 = QtWidgets.QHBoxLayout()
        self.IMUHLayout_2.setObjectName("IMUHLayout_2")
        self.XLabel0_2 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.XLabel0_2.setObjectName("XLabel0_2")
        self.IMUHLayout_2.addWidget(self.XLabel0_2)
        self.YLabel0_2 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.YLabel0_2.setObjectName("YLabel0_2")
        self.IMUHLayout_2.addWidget(self.YLabel0_2)
        self.ZLabel0_2 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.ZLabel0_2.setObjectName("ZLabel0_2")
        self.IMUHLayout_2.addWidget(self.ZLabel0_2)
        self.WLabel0_2 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.WLabel0_2.setObjectName("WLabel0_2")
        self.IMUHLayout_2.addWidget(self.WLabel0_2)
        self.IMULayout_2.addLayout(self.IMUHLayout_2)
        self.IMU_DISP_2 = QtWidgets.QHBoxLayout()
        self.IMU_DISP_2.setObjectName("IMU_DISP_2")
        self.X_DISP_4 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_13)
        self.X_DISP_4.setObjectName("X_DISP_4")
        self.IMU_DISP_2.addWidget(self.X_DISP_4)
        self.Y_DISP_4 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_13)
        self.Y_DISP_4.setObjectName("Y_DISP_4")
        self.IMU_DISP_2.addWidget(self.Y_DISP_4)
        self.Z_DISP_4 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_13)
        self.Z_DISP_4.setObjectName("Z_DISP_4")
        self.IMU_DISP_2.addWidget(self.Z_DISP_4)
        self.W_DISP_4 = QtWidgets.QLCDNumber(self.verticalLayoutWidget_13)
        self.W_DISP_4.setObjectName("W_DISP_4")
        self.IMU_DISP_2.addWidget(self.W_DISP_4)
        self.IMULayout_2.addLayout(self.IMU_DISP_2)
        self.verticalLayoutWidget_18 = QtWidgets.QWidget(self.ManualFlightManagment_Tab)
        self.verticalLayoutWidget_18.setGeometry(QtCore.QRect(10, 530, 301, 191))
        self.verticalLayoutWidget_18.setObjectName("verticalLayoutWidget_18")
        self.WaterSamplingLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_18)
        self.WaterSamplingLayout_2.setContentsMargins(0, 0, 0, 0)
        self.WaterSamplingLayout_2.setObjectName("WaterSamplingLayout_2")
        self.DesiredWaterSamplingPayloadCoordinates_2 = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        self.DesiredWaterSamplingPayloadCoordinates_2.setObjectName("DesiredWaterSamplingPayloadCoordinates_2")
        self.WaterSamplingLayout_2.addWidget(self.DesiredWaterSamplingPayloadCoordinates_2)
        self.WaterHLayout_2 = QtWidgets.QHBoxLayout()
        self.WaterHLayout_2.setObjectName("WaterHLayout_2")
        self.XLabel2_2 = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        self.XLabel2_2.setObjectName("XLabel2_2")
        self.WaterHLayout_2.addWidget(self.XLabel2_2)
        self.YLabel2_2 = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        self.YLabel2_2.setObjectName("YLabel2_2")
        self.WaterHLayout_2.addWidget(self.YLabel2_2)
        self.ZLabel2_2 = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        self.ZLabel2_2.setObjectName("ZLabel2_2")
        self.WaterHLayout_2.addWidget(self.ZLabel2_2)
        self.WLabel2_2 = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        self.WLabel2_2.setObjectName("WLabel2_2")
        self.WaterHLayout_2.addWidget(self.WLabel2_2)
        self.WaterSamplingLayout_2.addLayout(self.WaterHLayout_2)
        self.WaterHLayout1_2 = QtWidgets.QHBoxLayout()
        self.WaterHLayout1_2.setObjectName("WaterHLayout1_2")
        self.XPositionPayload_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_18)
        self.XPositionPayload_2.setObjectName("XPositionPayload_2")
        self.WaterHLayout1_2.addWidget(self.XPositionPayload_2)
        self.YPositionPayload_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_18)
        self.YPositionPayload_2.setObjectName("YPositionPayload_2")
        self.WaterHLayout1_2.addWidget(self.YPositionPayload_2)
        self.ZPositionPayload_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_18)
        self.ZPositionPayload_2.setObjectName("ZPositionPayload_2")
        self.WaterHLayout1_2.addWidget(self.ZPositionPayload_2)
        self.WPositionPayload_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_18)
        self.WPositionPayload_2.setObjectName("WPositionPayload_2")
        self.WaterHLayout1_2.addWidget(self.WPositionPayload_2)
        self.WaterSamplingLayout_2.addLayout(self.WaterHLayout1_2)
        WaterSamplingGroundControlStation.addTab(self.ManualFlightManagment_Tab, "")
        self.References_Tab = QtWidgets.QWidget()
        self.References_Tab.setObjectName("References_Tab")
        self.ReferencesTitle = QtWidgets.QLabel(self.References_Tab)
        self.ReferencesTitle.setGeometry(QtCore.QRect(20, 20, 151, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ReferencesTitle.setFont(font)
        self.ReferencesTitle.setObjectName("ReferencesTitle")
        self.ReferencesInfo = QtWidgets.QLabel(self.References_Tab)
        self.ReferencesInfo.setGeometry(QtCore.QRect(30, 80, 491, 661))
        self.ReferencesInfo.setWordWrap(True)
        self.ReferencesInfo.setObjectName("ReferencesInfo")
        WaterSamplingGroundControlStation.addTab(self.References_Tab, "")

        self.retranslateUi(WaterSamplingGroundControlStation)
        WaterSamplingGroundControlStation.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(WaterSamplingGroundControlStation)

    def retranslateUi(self, WaterSamplingGroundControlStation):
        _translate = QtCore.QCoreApplication.translate
        WaterSamplingGroundControlStation.setWindowTitle(_translate("WaterSamplingGroundControlStation", "TabWidget"))
        self.InitTitle.setText(_translate("WaterSamplingGroundControlStation", "UAV INITIALIZATION"))
        self.Welcome.setText(_translate("WaterSamplingGroundControlStation", "<html><head/><body><p>Welcome to the Water Sampling Ground Control Station! Here you will be able to set up, monitor and fly the UAV autonomously or manually. To fly, please start ROSCore, MAVROS and OFFBOARD for communication and control with UAV</p></body></html>"))
        self.ROSCoreInfo.setText(_translate("WaterSamplingGroundControlStation", "<html><head/><body><p>ROS Core </p><p>Roscore is a collection of nodes and programs that make up the pre-requisites of the robot operating system. You must have one and only one roscore running to be able to do any communication between nodes, and therefore communicate and fly the UAV [1]</p></body></html>"))
        self.StartROSCore.setText(_translate("WaterSamplingGroundControlStation", "Start ROS Core"))
        self.MAVROSInfo.setText(_translate("WaterSamplingGroundControlStation", "<html><head/><body><p>MAVROS</p><p>MAVROS is a package that provides communication drivers for various autopilots with the MAVLink protocol. It additionally provides the UDP MAVLink bridge for ground control stations such as QGroundControl. We harness the same communication to generate this ground control station.<br/></p></body></html>"))
        self.StartMAVROS.setText(_translate("WaterSamplingGroundControlStation", "Start MAVROS Communication"))
        self.OFFBOARDInfo.setText(_translate("WaterSamplingGroundControlStation", "<html><head/><body><p>OFFBOARD</p><p>Offboard mode is a function supported by all Pixhawk flight controllers except the 3DR Pixhawk1 [3]. It allows the vehicle to obey position, velocity, accleeration, attitude, altitude rates or thrust setpoints provided by an external source to the flight stack such as a companion computer. In this case we use Jetson Nano to run the flight controller and communicate the data over the MAVLink protocal. [4]</p></body></html>"))
        self.StartOffboard.setText(_translate("WaterSamplingGroundControlStation", "Start OFFBOARD MODE"))
        WaterSamplingGroundControlStation.setTabText(WaterSamplingGroundControlStation.indexOf(self.Initialization_Tab), _translate("WaterSamplingGroundControlStation", "Initilization"))
        self.AutonomousTitle.setText(_translate("WaterSamplingGroundControlStation", "Autonomous Flight"))
        self.GPSLabel.setText(_translate("WaterSamplingGroundControlStation", "Global Position"))
        self.LatLabel.setText(_translate("WaterSamplingGroundControlStation", "Lateral"))
        self.LongLabel.setText(_translate("WaterSamplingGroundControlStation", "Longitudinal"))
        self.AltLabel.setText(_translate("WaterSamplingGroundControlStation", "Altitude (MSL)"))
        self.IMULabel.setText(_translate("WaterSamplingGroundControlStation", "IMU (Orientation °)"))
        self.XLabel0.setText(_translate("WaterSamplingGroundControlStation", "Roll"))
        self.YLabel0.setText(_translate("WaterSamplingGroundControlStation", "Pitch"))
        self.ZLabel0.setText(_translate("WaterSamplingGroundControlStation", "Yaw"))
        self.VelLabel.setText(_translate("WaterSamplingGroundControlStation", "Velocity"))
        self.U_VEL_Label.setText(_translate("WaterSamplingGroundControlStation", "U"))
        self.V_VEL_Label.setText(_translate("WaterSamplingGroundControlStation", "V"))
        self.W_VEL_Label.setText(_translate("WaterSamplingGroundControlStation", "W"))
        self.FlightTimeLabel.setText(_translate("WaterSamplingGroundControlStation", "Flight Time"))
        self.Min_Label.setText(_translate("WaterSamplingGroundControlStation", "Minutes"))
        self.Sec_Label.setText(_translate("WaterSamplingGroundControlStation", "Seconds"))
        self.FlightLogTitle.setText(_translate("WaterSamplingGroundControlStation", "Flight Log"))
        self.DesiredFlightCoordinates.setText(_translate("WaterSamplingGroundControlStation", "Desired Flight Coordinates"))
        self.XLabel1.setText(_translate("WaterSamplingGroundControlStation", "X"))
        self.YLabel1.setText(_translate("WaterSamplingGroundControlStation", "Y"))
        self.ZLabel1.setText(_translate("WaterSamplingGroundControlStation", "Z"))
        self.GetCurrentPositionUAV.setText(_translate("WaterSamplingGroundControlStation", "Get Current Position"))
        self.EmergencyStop.setText(_translate("WaterSamplingGroundControlStation", "Emergency Stop"))
        self.SendPositionUAV.setText(_translate("WaterSamplingGroundControlStation", "Send New Position"))
        self.GetCurrentPositionPayload.setText(_translate("WaterSamplingGroundControlStation", "Get  Pos. Payload"))
        self.DesiredWaterSamplingPayloadCoordinates.setText(_translate("WaterSamplingGroundControlStation", "<html><head/><body><p align=\"center\">Desired Water Sampling </p><p align=\"center\">Payload Coordinates</p></body></html>"))
        self.XLabel2.setText(_translate("WaterSamplingGroundControlStation", "X"))
        self.YLabel2.setText(_translate("WaterSamplingGroundControlStation", "Y"))
        self.ZLabel2.setText(_translate("WaterSamplingGroundControlStation", "Z"))
        self.SendPositionPayload.setText(_translate("WaterSamplingGroundControlStation", "Send pos. Payload"))
        self.GPSLabel_2.setText(_translate("WaterSamplingGroundControlStation", "Relative Position"))
        self.LatLabel_2.setText(_translate("WaterSamplingGroundControlStation", "X"))
        self.LongLabel_2.setText(_translate("WaterSamplingGroundControlStation", "Y"))
        self.AltLabel_2.setText(_translate("WaterSamplingGroundControlStation", "Altitude (AGL)"))
        self.AutonomousTitle_2.setText(_translate("WaterSamplingGroundControlStation", "Controls"))
        self.Voltage_Label.setText(_translate("WaterSamplingGroundControlStation", "Voltage:"))
        self.StateConnected.setText(_translate("WaterSamplingGroundControlStation", "DISCONNECTED"))
        self.StateARM.setText(_translate("WaterSamplingGroundControlStation", "DISARMED"))
        self.StateMode.setText(_translate("WaterSamplingGroundControlStation", "MODE"))
        self.Takeoff.setText(_translate("WaterSamplingGroundControlStation", "Takeoff"))
        self.DISARM.setText(_translate("WaterSamplingGroundControlStation", "Disarm"))
        self.SimulationMode.setText(_translate("WaterSamplingGroundControlStation", "Simulation Mode"))
        self.ARM.setText(_translate("WaterSamplingGroundControlStation", "Arm"))
        self.TakeoffHeight.setText(_translate("WaterSamplingGroundControlStation", "2.0"))
        self.SetHome.setText(_translate("WaterSamplingGroundControlStation", "Set Home"))
        self.Land.setText(_translate("WaterSamplingGroundControlStation", "Land"))
        WaterSamplingGroundControlStation.setTabText(WaterSamplingGroundControlStation.indexOf(self.AutonomousFlightMode_Tab), _translate("WaterSamplingGroundControlStation", "Autonomous Flight"))
        self.ManualFlightTitle.setText(_translate("WaterSamplingGroundControlStation", "Manual Flight"))
        self.FlightTimeLabel_4.setText(_translate("WaterSamplingGroundControlStation", "Flight Time"))
        self.Min_Label_4.setText(_translate("WaterSamplingGroundControlStation", "Minutes"))
        self.Sec_Label_4.setText(_translate("WaterSamplingGroundControlStation", "Seconds"))
        self.GPSLabel_4.setText(_translate("WaterSamplingGroundControlStation", "GPS"))
        self.LatLabel_4.setText(_translate("WaterSamplingGroundControlStation", "Lateral"))
        self.LongLabel_4.setText(_translate("WaterSamplingGroundControlStation", "Longitudinal"))
        self.AltLabel_4.setText(_translate("WaterSamplingGroundControlStation", "Altitude"))
        self.BatLabel_4.setText(_translate("WaterSamplingGroundControlStation", "Battery Level"))
        self.FlightLogTitle_2.setText(_translate("WaterSamplingGroundControlStation", "Flight Log"))
        self.GetCurrentPositionUAV_2.setText(_translate("WaterSamplingGroundControlStation", "Get Current Position"))
        self.GetCurrentPositionPayload_2.setText(_translate("WaterSamplingGroundControlStation", "Get  Pos. Payload"))
        self.SendPositionPayload_2.setText(_translate("WaterSamplingGroundControlStation", "Send pos. Payload"))
        self.DesiredFlightCoordinates_2.setText(_translate("WaterSamplingGroundControlStation", "Desired Flight Coordinates"))
        self.XLabel1_2.setText(_translate("WaterSamplingGroundControlStation", "X"))
        self.YLabel1_2.setText(_translate("WaterSamplingGroundControlStation", "Y"))
        self.ZLabel1_2.setText(_translate("WaterSamplingGroundControlStation", "Z"))
        self.WLabel1_2.setText(_translate("WaterSamplingGroundControlStation", "W"))
        self.SendPositionUAV_2.setText(_translate("WaterSamplingGroundControlStation", "Send New Position"))
        self.FlightDistLabel_4.setText(_translate("WaterSamplingGroundControlStation", "Flight Distance"))
        self.Meters_Label_4.setText(_translate("WaterSamplingGroundControlStation", "Meters"))
        self.VelLabel_4.setText(_translate("WaterSamplingGroundControlStation", "Velocity"))
        self.U_VEL_Label_4.setText(_translate("WaterSamplingGroundControlStation", "U"))
        self.V_VEL_Label_4.setText(_translate("WaterSamplingGroundControlStation", "V"))
        self.W_VEL_Label_4.setText(_translate("WaterSamplingGroundControlStation", "W"))
        self.EmergencyStop_2.setText(_translate("WaterSamplingGroundControlStation", "Emergency Stop"))
        self.IMULabel_4.setText(_translate("WaterSamplingGroundControlStation", "IMU"))
        self.XLabel0_2.setText(_translate("WaterSamplingGroundControlStation", "X"))
        self.YLabel0_2.setText(_translate("WaterSamplingGroundControlStation", "Y"))
        self.ZLabel0_2.setText(_translate("WaterSamplingGroundControlStation", "Z"))
        self.WLabel0_2.setText(_translate("WaterSamplingGroundControlStation", "W"))
        self.DesiredWaterSamplingPayloadCoordinates_2.setText(_translate("WaterSamplingGroundControlStation", "<html><head/><body><p align=\"center\">Desired Water Sampling </p><p align=\"center\">Payload Coordinates</p></body></html>"))
        self.XLabel2_2.setText(_translate("WaterSamplingGroundControlStation", "X"))
        self.YLabel2_2.setText(_translate("WaterSamplingGroundControlStation", "Y"))
        self.ZLabel2_2.setText(_translate("WaterSamplingGroundControlStation", "Z"))
        self.WLabel2_2.setText(_translate("WaterSamplingGroundControlStation", "W"))
        WaterSamplingGroundControlStation.setTabText(WaterSamplingGroundControlStation.indexOf(self.ManualFlightManagment_Tab), _translate("WaterSamplingGroundControlStation", "Manual Flight"))
        self.ReferencesTitle.setText(_translate("WaterSamplingGroundControlStation", "References"))
        self.ReferencesInfo.setText(_translate("WaterSamplingGroundControlStation", "<html><head/><body><p>[1] https://wiki.ros.org/roscore</p><p>[2] https://wiki.ros.org/mavros</p><p>[3] https://docs.px4.io/main/en/flight_controller/pixhawk.html</p><p>[4] https://docs.px4.io/main/en/flight_modes/offboard.html</p></body></html>"))
        WaterSamplingGroundControlStation.setTabText(WaterSamplingGroundControlStation.indexOf(self.References_Tab), _translate("WaterSamplingGroundControlStation", "References"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WaterSamplingGroundControlStation = QtWidgets.QTabWidget()
    ui = Ui_WaterSamplingGroundControlStation()
    ui.setupUi(WaterSamplingGroundControlStation)
    WaterSamplingGroundControlStation.show()
    sys.exit(app.exec_())
